export type Lang = "en" | "hi";

const MONTHS: Record<string, string> = {
  January: "जनवरी",
  February: "फरवरी",
  March: "मार्च",
  April: "अप्रैल",
  May: "मई",
  June: "जून",
  July: "जुलाई",
  August: "अगस्त",
  September: "सितंबर",
  October: "अक्टूबर",
  November: "नवंबर",
  December: "दिसंबर",
  Jan: "जनवरी",
  Feb: "फरवरी",
  Mar: "मार्च",
  Apr: "अप्रैल",
  Jun: "जून",
  Jul: "जुलाई",
  Aug: "अगस्त",
  Sep: "सितंबर",
  Oct: "अक्टूबर",
  Nov: "नवंबर",
  Dec: "दिसंबर",
};

const PHRASES: Record<string, string> = {
  "Latest Job": "नवीनतम नौकरी",
  Result: "परिणाम",
  "Admit Card": "एडमिट कार्ड",
  "Answer Key": "उत्तर कुंजी",
  Syllabus: "पाठ्यक्रम",
  Admission: "प्रवेश",
  Certificate: "प्रमाण पत्र",
  Important: "महत्वपूर्ण",
  Latest: "नवीनतम",
  "All levels": "सभी स्तर",
  "10th / ITI": "दसवीं / आईटीआई",
  "12th": "बारहवीं",
  Graduate: "स्नातक",
  "Online forms and recruitment notices. Apply only on the board’s own site.": "ऑनलाइन फॉर्म और भर्ती सूचनाएँ। आवेदन केवल बोर्ड की अपनी साइट पर करें।",
  "Written, mains, and final results, with the official score link.": "लिखित, मुख्य और अंतिम परिणाम, आधिकारिक स्कोर लिंक के साथ।",
  "Hall tickets, city slips, and exam-date notices.": "हॉल टिकट, सिटी स्लिप और परीक्षा-तिथि सूचनाएँ।",
  "Tentative keys and challenge windows.": "अस्थायी कुंजी और आपत्ति खिड़की।",
  "Exam pattern and subject outlines as published by the board.": "बोर्ड द्वारा जारी परीक्षा पैटर्न और विषय रूपरेखा।",
  "Entrance forms and correction windows for courses and national tests.": "पाठ्यक्रम और राष्ट्रीय परीक्षाओं के प्रवेश फॉर्म और सुधार विंडो।",
  "E-certificates and marksheets hosted by the examining body.": "परीक्षा संस्था द्वारा जारी ई-प्रमाण पत्र और अंकपत्र।",
  "Calendars and desk notes that are not a single recruitment.": "कैलेंडर और नोट, जो एक भर्ती नहीं हैं।",
  Out: "जारी",
  New: "नया",
  Closed: "बंद",
  "Last date today": "अंतिम तिथि आज",
  "Age limit": "आयु सीमा",
  "Post date": "प्रकाशन तिथि",
  Confirm: "पुष्टि करें",
  "Notification date": "अधिसूचना तिथि",
  "Online apply start": "ऑनलाइन आवेदन शुरू",
  "Online apply last date": "ऑनलाइन आवेदन की अंतिम तिथि",
  "Online apply start date": "ऑनलाइन आवेदन शुरू",
  "Apply start": "आवेदन शुरू",
  "Apply last date": "आवेदन की अंतिम तिथि",
  "Apply window": "आवेदन अवधि",
  "Fee last date": "शुल्क की अंतिम तिथि",
  "Last date for fee payment": "शुल्क भुगतान की अंतिम तिथि",
  "Correction window": "सुधार विंडो",
  "Exam date": "परीक्षा तिथि",
  "Admit card": "एडमिट कार्ड",
  Exam: "परीक्षा",
  CBT: "सीबीटी",
  "CBT-II exam date": "सीबीटी-II परीक्षा तिथि",
  "CBT-II result": "सीबीटी-II परिणाम",
  "CBAT exam date": "सीबीएटी परीक्षा तिथि",
  "Result date": "परिणाम तिथि",
  "Result window": "परिणाम अवधि",
  "Written result": "लिखित परिणाम",
  "Main result": "मुख्य परिणाम",
  "Score link": "स्कोर लिंक",
  "Call letter": "कॉल लेटर",
  "Notice date": "सूचना तिथि",
  "PET admit card": "पीईटी एडमिट कार्ड",
  "Stage I admit card": "चरण-I एडमिट कार्ड",
  "Written admit card": "लिखित परीक्षा एडमिट कार्ड",
  "Key published": "कुंजी जारी",
  "Challenge window": "आपत्ति खिड़की",
  "Tentative key": "अस्थायी कुंजी",
  Key: "कुंजी",
  "Answer key": "उत्तर कुंजी",
  "Key cycle": "कुंजी चक्र",
  Scheme: "योजना",
  Calendar: "कैलेंडर",
  "Calendar PDF": "कैलेंडर पीडीएफ",
  "E-certificate": "ई-प्रमाण पत्र",
  "Marks link": "अंक लिंक",
  Rule: "नियम",
  Course: "कोर्स",
  "Posts circulated": "घोषित पद",
  "All categories": "सभी वर्ग",
  Payment: "भुगतान",
  "General / OBC": "सामान्य / ओबीसी",
  "SC / ST / PwBD / ex-servicemen": "एससी / एसटी / दिव्यांग / भूतपूर्व सैनिक",
  "SC / ST / women / PwBD / ex-servicemen": "एससी / एसटी / महिला / दिव्यांग / भूतपूर्व सैनिक",
  "Women / SC / ST / PwBD / ex-servicemen": "महिला / एससी / एसटी / दिव्यांग / भूतपूर्व सैनिक",
  "Minimum age": "न्यूनतम आयु",
  "Maximum age": "अधिकतम आयु",
  Relaxation: "छूट",
  "Age window": "आयु सीमा",
  "General range": "सामान्य सीमा",
  "Minimum, classes 1–8": "न्यूनतम, कक्षा 1–8",
  "Minimum, classes 9–12": "न्यूनतम, कक्षा 9–12",
  "Maximum, UR male": "अधिकतम, अनारक्षित पुरुष",
  "Maximum, UR female": "अधिकतम, अनारक्षित महिला",
  "Maximum, BC / EBC": "अधिकतम, बीसी / ईबीसी",
  "Maximum, SC / ST": "अधिकतम, एससी / एसटी",
  "Total circulated": "कुल घोषित",
  "School teacher, classes 1–5": "स्कूल शिक्षक, कक्षा 1–5",
  "School teacher, classes 6–8": "स्कूल शिक्षक, कक्षा 6–8",
  "School teacher, classes 9–10": "स्कूल शिक्षक, कक्षा 9–10",
  "School teacher, classes 11–12": "स्कूल शिक्षक, कक्षा 11–12",
  "Classes 1–5": "कक्षा 1–5",
  "Classes 6–8": "कक्षा 6–8",
  "Classes 9–12": "कक्षा 9–12",
  "All posts": "सभी पद",
  "Army wing": "थल सेना विंग",
  "Navy and Air Force wings": "नौसेना और वायु सेना विंग",
  Engineering: "इंजीनियरिंग",
  "Navik (General Duty)": "नाविक (जनरल ड्यूटी)",
  Yantrik: "यंत्रिक",
  Clerk: "लिपिक",
  "Junior accountant": "कनिष्ठ लेखाकार",
  "PCS posts": "पीसीएस पद",
  "State service": "राज्य सेवा",
  SSR: "एसएसआर",
  "Flying / ground duty": "फ्लाइंग / ग्राउंड ड्यूटी",
  Technical: "तकनीकी",
  "MTS and Havaldar": "एमटीएस और हवलदार",
  "Graduate level": "स्नातक स्तर",
  "Graduate level NTPC posts": "स्नातक स्तर एनटीपीसी पद",
  "Undergraduate posts": "स्नातक-पूर्व पद",
  "Nursing officer": "नर्सिंग अधिकारी",
  "Assistant Loco Pilot (ALP)": "सहायक लोको पायलट (एएलपी)",
  Primary: "प्राथमिक",
  Secondary: "माध्यमिक",
  Prelims: "प्रारंभिक",
  Mains: "मुख्य",
  "Tier I": "टियर I",
  "Tier II": "टियर II",
  Mathematics: "गणित",
  GAT: "जीएटी",
  "Later stage": "अगला चरण",
  "RRB apply portal": "आरआरबी आवेदन पोर्टल",
  "RRB Chandigarh official website": "आरआरबी चंडीगढ़ आधिकारिक वेबसाइट",
  "Check application status": "आवेदन स्थिति देखें",
  "SSC official website": "एसएससी आधिकारिक वेबसाइट",
  "UPSC official website": "यूपीएससी आधिकारिक वेबसाइट",
  "IBPS official website": "आईबीपीएस आधिकारिक वेबसाइट",
  "See the official notice": "आधिकारिक सूचना देखें",
  "See notice": "सूचना देखें",
  "Printed in the official notification.": "आधिकारिक अधिसूचना में छपा है।",
  "See the official notification for the stages that apply to this post.": "इस पद के चरण आधिकारिक अधिसूचना में देखें।",
  "Not collected here. The original notice on the official website states the fee.": "यहाँ शुल्क नहीं लिया जाता। शुल्क आधिकारिक सूचना में लिखा है।",
  "Fixed in the original notification. Use the as-on date printed there.": "आयु मूल अधिसूचना में तय है। वहीं छपी तिथि देखें।",
  "As printed on the CEN": "सीईएन में छपा हुआ",
  "Reduced fee as printed on the CEN": "सीईएन के अनुसार कम शुल्क",
  "As printed on the UPSC notice": "यूपीएससी सूचना के अनुसार",
  "Nil, as per the SSC notice": "शून्य, एसएससी सूचना के अनुसार",
  "To be notified by BPSC": "बीपीएससी द्वारा बाद में घोषित",
  "Before the exam": "परीक्षा से पहले",
  "Before the exam, on the BPSC site": "परीक्षा से पहले, बीपीएससी साइट पर",
  "On the SSC exam calendar": "एसएससी परीक्षा कैलेंडर पर",
  "As per the RRB city slip": "आरआरबी सिटी स्लिप के अनुसार",
  "As given on the UPSC calendar": "यूपीएससी कैलेंडर के अनुसार",
  "Named in the CEN after the last date": "अंतिम तिथि के बाद सीईएन में",
  "On the date printed on your card": "आपके कार्ड पर छपी तिथि",
  "Notify later": "बाद में घोषित",
  "The dates printed on the SSC notice": "एसएससी सूचना में छपी तिथियाँ",
  "After the written exam": "लिखित परीक्षा के बाद",
  "Published with the CHSL 2026 notice": "सीएचएसएल 2026 सूचना के साथ",
  "Closes 12 October 2026": "12 अक्टूबर 2026 को बंद",
  "October 2026": "अक्टूबर 2026",
  "September 2026": "सितंबर 2026",
  "1 October 2026, now available on regional RRBs": "1 अक्टूबर 2026, क्षेत्रीय आरआरबी पर उपलब्ध",
  "30 October 2026, as circulated": "30 अक्टूबर 2026, यथा प्रसारित",
  "22–31 May 2025": "22–31 मई 2025",
  "July 2027 batch, as circulated": "जुलाई 2027 बैच, यथा प्रसारित",
  "About 1,590": "लगभग 1,590",
  "7,466": "7,466",
  "10,970": "10,970",
  "33,320": "33,320",
  "3,548 across RRBs": "आरआरबी में कुल 3,548",
  "₹100": "₹100",
  "₹500": "₹500",
  "₹250": "₹250",
  "18 years": "18 वर्ष",
  "30 years": "30 वर्ष",
  "21 years": "21 वर्ष",
  "37 years": "37 वर्ष",
  "40 years": "40 वर्ष",
  "42 years": "42 वर्ष",
  "Debit card, credit card, net banking, or wallet on the BPSC portal": "बीपीएससी पोर्टल पर डेबिट कार्ड, क्रेडिट कार्ड, नेट बैंकिंग या वॉलेट",
  "See district roster on the notice": "सूचना का जिला रोस्टर देखें",
  "18 to 33 years, with relaxation by category and post": "18 से 33 वर्ष, वर्ग और पद के अनुसार छूट",
  "About 16.5 to 19.5 years. Read the exact dates; they change with each exam.": "लगभग 16.5 से 19.5 वर्ष। सटीक तिथियाँ हर परीक्षा में बदलती हैं।",
  "As per railway rules for the category printed in CEN 01/2025": "सीईएन 01/2025 में छपे वर्ग के रेलवे नियम के अनुसार",
  "Preliminary exam": "प्रारंभिक परीक्षा",
  "Main exam": "मुख्य परीक्षा",
  "Merit list": "मेरिट सूची",
  "Document verification": "दस्तावेज़ सत्यापन",
  "Computer based test": "कंप्यूटर आधारित परीक्षा",
  "Skill test or aptitude test where the post requires it": "जहाँ पद माँगे, कौशल या अभिरुचि परीक्षा",
  "Medical exam": "चिकित्सा परीक्षा",
  "Typing skill test where required": "जहाँ आवश्यक हो, टाइपिंग परीक्षा",
  "Tier I CBT": "टियर I सीबीटी",
  "Skill test for DEO / typing posts": "डीईओ / टाइपिंग पदों की कौशल परीक्षा",
  "Written exam": "लिखित परीक्षा",
  "SSB interview": "एसएसबी साक्षात्कार",
  "Medical examination": "चिकित्सा परीक्षण",
  "Shortlisting on engineering marks": "इंजीनियरिंग अंकों पर शॉर्टलिस्ट",
  SSB: "एसएसबी",
  Medical: "मेडिकल",
  "CBT-I": "सीबीटी-I",
  "CBT-II": "सीबीटी-II",
  "CBAT (computer-based aptitude test)": "सीबीएटी (कंप्यूटर आधारित अभिरुचि परीक्षा)",
  "Document verification and medical examination": "दस्तावेज़ सत्यापन और चिकित्सा परीक्षण",
  "RRB Mumbai": "आरआरबी मुंबई",
  "RRB Ranchi": "आरआरबी रांची",
  "RRB Patna": "आरआरबी पटना",
  "RRB Muzaffarpur": "आरआरबी मुजफ्फरपुर",
  "RRB Ahmedabad": "आरआरबी अहमदाबाद",
  "RRB Prayagraj": "आरआरबी प्रयागराज",
  "RRB Gorakhpur": "आरआरबी गोरखपुर",
  "RRB Bhopal": "आरआरबी भोपाल",
  "RRB Ajmer": "आरआरबी अजमेर",
  "RRB Chandigarh": "आरआरबी चंडीगढ़",
  "RRB Kolkata": "आरआरबी कोलकाता",
  "RRB Bengaluru": "आरआरबी बेंगलुरु",
};

const TITLES: Record<string, string> = {
  "BPSC School Teacher TRE 4.0 Online Form (33,320 posts)": "बीपीएससी स्कूल शिक्षक टीआरई 4.0 ऑनलाइन फॉर्म (33,320 पद)",
  "BPSC School Teacher TRE 4.0 Recruitment 2026": "बीपीएससी स्कूल शिक्षक टीआरई 4.0 भर्ती 2026",
  "RRB NTPC Graduate Level Online Form (3,548 posts)": "आरआरबी एनटीपीसी स्नातक स्तर ऑनलाइन फॉर्म (3,548 पद)",
  "RRB NTPC Graduate Level Recruitment 2026": "आरआरबी एनटीपीसी स्नातक स्तर भर्ती 2026",
  "RRB NTPC 10+2 Under Graduate Online Form (1,688 posts)": "आरआरबी एनटीपीसी 10+2 स्नातक-पूर्व ऑनलाइन फॉर्म (1,688 पद)",
  "RRB NTPC Undergraduate Recruitment 2026": "आरआरबी एनटीपीसी स्नातक-पूर्व भर्ती 2026",
  "SSC CHSL 10+2 Online Form 2026": "एसएससी सीएचएसएल 10+2 ऑनलाइन फॉर्म 2026",
  "SSC Combined Higher Secondary Level Examination 2026": "एसएससी संयुक्त उच्चतर माध्यमिक स्तर परीक्षा 2026",
  "UPSC NDA II 2026 Online Form": "यूपीएससी एनडीए II 2026 ऑनलाइन फॉर्म",
  "UPSC National Defence Academy & Naval Academy Examination (II) 2026": "यूपीएससी राष्ट्रीय रक्षा अकादमी और नौसेना अकादमी परीक्षा (II) 2026",
  "Indian Army TGC 145 Online Form": "भारतीय सेना टीजीसी 145 ऑनलाइन फॉर्म",
  "Indian Army Technical Graduate Course 145": "भारतीय सेना तकनीकी स्नातक कोर्स 145",
  "Indian Coast Guard CGEPT 01/2027 & 02/2027 Online Form": "भारतीय तटरक्षक सीजीईपीटी 01/2027 और 02/2027 ऑनलाइन फॉर्म",
  "Coast Guard Enrolled Persons Test, Batches 01/2027 and 02/2027": "तटरक्षक भर्ती परीक्षा, बैच 01/2027 और 02/2027",
  "IBPS Clerk CSA XVI Online Form": "आईबीपीएस लिपिक सीएसए XVI ऑनलाइन फॉर्म",
  "IBPS Clerk (Customer Service Associate) CRP CSA XVI": "आईबीपीएस लिपिक (कस्टमर सर्विस एसोसिएट) सीआरपी सीएसए XVI",
  "RPSC Junior Accountant Online Form": "आरपीएससी कनिष्ठ लेखाकार ऑनलाइन फॉर्म",
  "RPSC Junior Accountant Recruitment 2026": "आरपीएससी कनिष्ठ लेखाकार भर्ती 2026",
  "UPPSC Combined State / Upper Subordinate Online Form": "यूपीपीएससी संयुक्त राज्य / अपर अधीनस्थ ऑनलाइन फॉर्म",
  "UPPSC PCS Combined State Examination 2026": "यूपीपीएससी पीसीएस संयुक्त राज्य परीक्षा 2026",
  "MPPSC State Service Online Form": "एमपीपीएससी राज्य सेवा ऑनलाइन फॉर्म",
  "MPPSC State Service Examination 2026": "एमपीपीएससी राज्य सेवा परीक्षा 2026",
  "Indian Navy Agniveer SSR Online Form": "भारतीय नौसेना अग्निवीर एसएसआर ऑनलाइन फॉर्म",
  "Indian Navy Agniveer SSR Intake 2026": "भारतीय नौसेना अग्निवीर एसएसआर भर्ती 2026",
  "AFCAT 02/2027 Online Form": "एएफसीएटी 02/2027 ऑनलाइन फॉर्म",
  "Indian Air Force AFCAT 02/2027": "भारतीय वायु सेना एएफसीएटी 02/2027",
  "SSC MTS & Havaldar Online Form 2026": "एसएससी एमटीएस और हवलदार ऑनलाइन फॉर्म 2026",
  "SSC Multi Tasking Staff and Havaldar Examination 2026": "एसएससी मल्टी टास्किंग स्टाफ और हवलदार परीक्षा 2026",
  "SSC Stenographer C, D 2025 Final Result — Out": "एसएससी आशुलिपिक सी, डी 2025 अंतिम परिणाम — जारी",
  "SSC Stenographer Grade C & D Examination 2025 Final Result": "एसएससी आशुलिपिक ग्रेड सी और डी परीक्षा 2025 अंतिम परिणाम",
  "SSC CHSL 2025 Final Result — Out": "एसएससी सीएचएसएल 2025 अंतिम परिणाम — जारी",
  "SSC CHSL 10+2 Examination 2025 Final Result": "एसएससी सीएचएसएल 10+2 परीक्षा 2025 अंतिम परिणाम",
  "SSC MTS / Havaldar Final Result 2026 — Out": "एसएससी एमटीएस / हवलदार अंतिम परिणाम 2026 — जारी",
  "SSC MTS and Havaldar Final Result 2026": "एसएससी एमटीएस और हवलदार अंतिम परिणाम 2026",
  "RRB ALP CBT-II Result 2026 — Out": "आरआरबी एएलपी सीबीटी-II परिणाम 2026 — जारी",
  "RRB ALP CBT-II Result 2026": "आरआरबी एएलपी सीबीटी-II परिणाम 2026",
  "UPPSC LT Grade Teacher Mains Result 2026": "यूपीपीएससी एलटी ग्रेड शिक्षक मुख्य परिणाम 2026",
  "UPPSC LT Grade Assistant Teacher Mains Result 2026": "यूपीपीएससी एलटी ग्रेड सहायक शिक्षक मुख्य परिणाम 2026",
  "IBPS RRB Office Assistant Result 2026": "आईबीपीएस आरआरबी कार्यालय सहायक परिणाम 2026",
  "IBPS RRB Office Assistant Prelims Result 2026": "आईबीपीएस आरआरबी कार्यालय सहायक प्रारंभिक परिणाम 2026",
  "BPSC 70th CCE Prelims Result": "बीपीएससी 70वीं सीसीई प्रारंभिक परिणाम",
  "BPSC 70th Combined Competitive Prelims Result": "बीपीएससी 70वीं संयुक्त प्रतियोगी प्रारंभिक परिणाम",
  "RPSC Sub Inspector Result 2026": "आरपीएससी उप निरीक्षक परिणाम 2026",
  "RPSC Sub Inspector Recruitment Result 2026": "आरपीएससी उप निरीक्षक भर्ती परिणाम 2026",
  "MPPSC Forest Service Result 2026": "एमपीपीएससी वन सेवा परिणाम 2026",
  "MPPSC Forest Service Main Result 2026": "एमपीपीएससी वन सेवा मुख्य परिणाम 2026",
  "UPSC CDS II Written Result 2026": "यूपीएससी सीडीएस II लिखित परिणाम 2026",
  "UPSC Combined Defence Services Examination (II) 2026 Written Result": "यूपीएससी संयुक्त रक्षा सेवा परीक्षा (II) 2026 लिखित परिणाम",
  "Navy Agniveer SSR Written Result 2026": "नौसेना अग्निवीर एसएसआर लिखित परिणाम 2026",
  "Indian Navy Agniveer SSR Written Exam Result 2026": "भारतीय नौसेना अग्निवीर एसएसआर लिखित परीक्षा परिणाम 2026",
  "SSC CGL Tier-I Admit Card 2026": "एसएससी सीजीएल टियर-I एडमिट कार्ड 2026",
  "IBPS Clerk Pre Admit Card 2026": "आईबीपीएस लिपिक प्री एडमिट कार्ड 2026",
  "IBPS Clerk Prelims Admit Card 2026": "आईबीपीएस लिपिक प्रारंभिक एडमिट कार्ड 2026",
  "RRB Technician Admit Card 2026": "आरआरबी टेक्निशियन एडमिट कार्ड 2026",
  "UPPSC RO / ARO Admit Card 2026": "यूपीपीएससी आरओ / एआरओ एडमिट कार्ड 2026",
  "UPPSC Review Officer and Assistant Review Officer Admit Card 2026": "यूपीपीएससी समीक्षा अधिकारी और सहायक समीक्षा अधिकारी एडमिट कार्ड 2026",
  "AFCAT Admit Card 2026": "एएफसीएटी एडमिट कार्ड 2026",
  "AFCAT Admit Card for the Current Entry": "वर्तमान प्रवेश का एएफसीएटी एडमिट कार्ड",
  "UPSC CAPF AC Admit Card 2026": "यूपीएससी सीएपीएफ एसी एडमिट कार्ड 2026",
  "UPSC CAPF Assistant Commandant Admit Card 2026": "यूपीएससी सीएपीएफ सहायक कमांडेंट एडमिट कार्ड 2026",
  "BPSC School Teacher Exam Date Notice": "बीपीएससी स्कूल शिक्षक परीक्षा तिथि सूचना",
  "BPSC TRE 4.0 Exam Date Notice": "बीपीएससी टीआरई 4.0 परीक्षा तिथि सूचना",
  "SSC GD Constable PET Admit Card 2026": "एसएससी जीडी कांस्टेबल पीईटी एडमिट कार्ड 2026",
  "SSC GD Constable PET / PST Admit Card 2026": "एसएससी जीडी कांस्टेबल पीईटी / पीएसटी एडमिट कार्ड 2026",
  "RPSC School Lecturer Admit Card 2026": "आरपीएससी स्कूल लेक्चरर एडमिट कार्ड 2026",
  "MPPSC Prelims Admit Card 2026": "एमपीपीएससी प्रारंभिक एडमिट कार्ड 2026",
  "MPPSC State Service Prelims Admit Card 2026": "एमपीपीएससी राज्य सेवा प्रारंभिक एडमिट कार्ड 2026",
  "Navy Agniveer MR Admit Card 2026": "नौसेना अग्निवीर एमआर एडमिट कार्ड 2026",
  "Indian Navy Agniveer MR Admit Card 2026": "भारतीय नौसेना अग्निवीर एमआर एडमिट कार्ड 2026",
  "Coast Guard Navik Admit Card 2026": "तटरक्षक नाविक एडमिट कार्ड 2026",
  "Indian Coast Guard Navik Admit Card 2026": "भारतीय तटरक्षक नाविक एडमिट कार्ड 2026",
  "SSC Stenographer Tentative Answer Key 2026": "एसएससी आशुलिपिक अस्थायी उत्तर कुंजी 2026",
  "SSC Stenographer Grade C & D 2026 Tentative Answer Key": "एसएससी आशुलिपिक ग्रेड सी और डी 2026 अस्थायी उत्तर कुंजी",
  "RRB NTPC CBT Answer Key 2026": "आरआरबी एनटीपीसी सीबीटी उत्तर कुंजी 2026",
  "RRB NTPC CBT Tentative Answer Key 2026": "आरआरबी एनटीपीसी सीबीटी अस्थायी उत्तर कुंजी 2026",
  "UPPSC PCS Prelims Answer Key 2026": "यूपीपीएससी पीसीएस प्रारंभिक उत्तर कुंजी 2026",
  "RPSC SET Answer Key 2026": "आरपीएससी सेट उत्तर कुंजी 2026",
  "Rajasthan State Eligibility Test Answer Key 2026": "राजस्थान राज्य पात्रता परीक्षा उत्तर कुंजी 2026",
  "BPSC School Teacher Answer Key": "बीपीएससी स्कूल शिक्षक उत्तर कुंजी",
  "BPSC TRE Answer Key and Objection Window": "बीपीएससी टीआरई उत्तर कुंजी और आपत्ति खिड़की",
  "SSC CHSL Tier I & II Syllabus 2026": "एसएससी सीएचएसएल टियर I और II पाठ्यक्रम 2026",
  "SSC CHSL Tier I and Tier II Syllabus": "एसएससी सीएचएसएल टियर I और टियर II पाठ्यक्रम",
  "RRB NTPC Graduate Syllabus 2026": "आरआरबी एनटीपीसी स्नातक पाठ्यक्रम 2026",
  "RRB NTPC Graduate Level Syllabus and Pattern": "आरआरबी एनटीपीसी स्नातक स्तर पाठ्यक्रम और पैटर्न",
  "BPSC School Teacher Syllabus 2026": "बीपीएससी स्कूल शिक्षक पाठ्यक्रम 2026",
  "BPSC TRE 4.0 Syllabus and Exam Pattern": "बीपीएससी टीआरई 4.0 पाठ्यक्रम और परीक्षा पैटर्न",
  "IBPS Clerk Syllabus 2026": "आईबीपीएस लिपिक पाठ्यक्रम 2026",
  "IBPS Clerk Prelims and Mains Syllabus": "आईबीपीएस लिपिक प्रारंभिक और मुख्य पाठ्यक्रम",
  "UPSC NDA Syllabus 2026": "यूपीएससी एनडीए पाठ्यक्रम 2026",
  "UPSC NDA Written Syllabus": "यूपीएससी एनडीए लिखित पाठ्यक्रम",
  "NTA CUET UG Correction Window 2026": "एनटीए सीयूईटी यूजी सुधार विंडो 2026",
  "CUET (UG) 2026 Application Correction": "सीयूईटी (यूजी) 2026 आवेदन सुधार",
  "AIIMS NORCET Nursing Officer Online Form": "एम्स नॉर्सेट नर्सिंग अधिकारी ऑनलाइन फॉर्म",
  "AIIMS NORCET Nursing Officer Recruitment 2026": "एम्स नॉर्सेट नर्सिंग अधिकारी भर्ती 2026",
  "CTET Certificate Download 2026": "सीटीईटी प्रमाण पत्र डाउनलोड 2026",
  "CTET Eligibility Certificate 2026": "सीटीईटी पात्रता प्रमाण पत्र 2026",
  "NTA UGC NET E-Certificate 2026": "एनटीए यूजीसी नेट ई-प्रमाण पत्र 2026",
  "UGC NET June 2026 E-Certificate": "यूजीसी नेट जून 2026 ई-प्रमाण पत्र",
  "SSC CGL 2025 Final Marks Download": "एसएससी सीजीएल 2025 अंतिम अंक डाउनलोड",
  "SSC CGL 2025 Marks and Rank": "एसएससी सीजीएल 2025 अंक और रैंक",
  "SSC Exam Calendar 2026–27": "एसएससी परीक्षा कैलेंडर 2026–27",
  "SSC Examination Calendar 2026–27": "एसएससी परीक्षा कैलेंडर 2026–27",
  "UPSC Exam Calendar 2026": "यूपीएससी परीक्षा कैलेंडर 2026",
  "UPSC Annual Examination Calendar": "यूपीएससी वार्षिक परीक्षा कैलेंडर",
  "IBPS Calendar 2026–27": "आईबीपीएस कैलेंडर 2026–27",
  "IBPS Examination Calendar 2026–27": "आईबीपीएस परीक्षा कैलेंडर 2026–27",
  "How to spot a fake recruitment notice": "नकली भर्ती सूचना कैसे पहचानें",
  "How to tell a real government notice from a fake one": "असली सरकारी सूचना को नकली से कैसे अलग करें",
};

const SUMMARIES: Record<string, string> = {
  "Bihar Public Service Commission has invited online applications for TRE 4.0 school teachers. The circulated vacancy is 33,320 posts across primary and secondary classes. Treat every figure below as a reading summary and match it to the PDF on the BPSC site before you pay the fee.":
    "बिहार लोक सेवा आयोग ने टीआरई 4.0 स्कूल शिक्षकों के लिए ऑनलाइन आवेदन माँगे हैं। घोषित रिक्ति प्राथमिक और माध्यमिक कक्षाओं में 33,320 पद है। नीचे का हर आँकड़ा पढ़ने का सार है। शुल्क से पहले बीपीएससी पीडीएफ से मिलाएँ।",
  "Railway Recruitment Boards have opened the graduate-level NTPC window for posts such as station master, goods train manager, and junior accounts assistant. Vacancies are divided by RRB. Apply on the railway candidate portal, not on this page.":
    "रेलवे भर्ती बोर्डों ने स्टेशन मास्टर, गुड्स ट्रेन मैनेजर और जूनियर अकाउंट्स असिस्टेंट जैसे पदों के लिए स्नातक एनटीपीसी खिड़की खोली है। रिक्तियाँ आरआरबी के अनुसार बँटी हैं। आवेदन रेलवे पोर्टल पर करें, इस पृष्ठ पर नहीं।",
  "The undergraduate NTPC CEN covers 12th-level commercial and clerical posts. The circulated total is 1,688. Check the RRB you opt for; a form filed on the wrong regional board is not transferred.":
    "स्नातक-पूर्व एनटीपीसी सीईएन में बारहवीं स्तर के वाणिज्यिक और लिपिकीय पद हैं। घोषित कुल 1,688 है। जिस आरआरबी को चुनें वही जाँचें। गलत क्षेत्रीय बोर्ड पर भरा फॉर्म नहीं जाता।",
  "SSC CHSL recruits LDC, JSA, and DEO posts for ministries and departments. Tier I is a computer-based test. The vacancy in circulation is about 2,536 and will move when departments add or withdraw posts.":
    "एसएससी सीएचएसएल मंत्रालयों के लिए एलडीसी, जेएसए और डीईओ पद भरता है। टियर I कंप्यूटर परीक्षा है। प्रसारित रिक्ति लगभग 2,536 है और विभाग पद जोड़ें या हटाएँ तो बदल सकती है।",
  "NDA II selects candidates for the Army, Navy, and Air Force wings of the National Defence Academy, and for the Naval Academy. The form closes on the UPSC website. Unmarried candidates who meet the age window should file only at upsconline.gov.in.":
    "एनडीए II राष्ट्रीय रक्षा अकादमी की थल, नौ और वायु सेना विंग तथा नौसेना अकादमी के लिए चुनता है। फॉर्म यूपीएससी साइट पर बंद होता है। आयु सीमा वाले अविवाहित अभ्यर्थी केवल upsconline.gov.in पर भरें।",
  "TGC 145 is a short-service technical entry for engineering graduates. The circulated vacancy is small, about 30, and branches depend on the engineering discipline. Apply on joinindianarmy.nic.in.":
    "टीजीसी 145 इंजीनियरिंग स्नातकों की शॉर्ट सर्विस तकनीकी प्रविष्टि है। घोषित रिक्ति लगभग 30 है और शाखा विषय पर निर्भर है। आवेदन joinindianarmy.nic.in पर करें।",
  "The Coast Guard has published the enrolled-persons test for the 2027 batches. Navik and Yantrik streams have different subject and height rules. A copy of the notice was also placed on the SSC notice board; the application itself belongs to the Coast Guard.":
    "तटरक्षक ने 2027 बैचों की भर्ती परीक्षा प्रकाशित की है। नाविक और यंत्रिक की विषय और ऊँचाई के नियम अलग हैं। सूचना की प्रति एसएससी बोर्ड पर भी रही; आवेदन तटरक्षक साइट पर है।",
  "IBPS is recruiting clerks, now styled customer service associates, for participating public sector banks. State-wise vacancies and local language are part of the form. Do not pay anyone who offers a “bank link” outside ibps.in.":
    "आईबीपीएस भागीदार सरकारी बैंकों के लिए लिपिक, अब कस्टमर सर्विस एसोसिएट, भर रहा है। राज्यवार रिक्ति और स्थानीय भाषा फॉर्म का हिस्सा हैं। ibps.in के बाहर “बैंक लिंक” देकर पैसे माँगने वाले को न दें।",
  "Rajasthan Public Service Commission has a junior accountant window closing within days of this desk edition. Commerce graduates should read the Rajasthan domicile and reservation rules on the RPSC notice before filing.":
    "राजस्थान लोक सेवा आयोग की कनिष्ठ लेखाकार खिड़की इस संस्करण के कुछ दिनों में बंद हो रही है। वाणिज्य स्नातक आवेदन से पहले आरपीएससी सूचना में निवास और आरक्षण नियम पढ़ें।",
  "The combined state exam is the main UPPSC recruitment for administrative and allied posts. Prelims is a screening test. Read the optional-subject rules and the UP domicile claim carefully; a wrong claim is rejected at verification.":
    "संयुक्त राज्य परीक्षा प्रशासनिक और संबद्ध पदों की मुख्य यूपीपीएससी भर्ती है। प्रारंभिक परीक्षा छँटनी है। वैकल्पिक विषय और उत्तर प्रदेश निवास का दावा ध्यान से पढ़ें। गलत दावा सत्यापन में कट जाता है।",
  "Madhya Pradesh Public Service Commission’s state service exam follows the prelims–mains–interview pattern. Vacancy by post is in the advertisement, not in the headline.":
    "मध्य प्रदेश लोक सेवा आयोग की राज्य सेवा परीक्षा प्रारंभिक–मुख्य–साक्षात्कार पर चलती है। पदवार रिक्ति विज्ञापन में है, शीर्षक में नहीं।",
  "Agniveer SSR is the 12th-with-science entry for the Navy’s four-year engagement. Height, eyesight, and the exact percentage in Physics and Mathematics are disqualifying if you miss them. Apply only on joinindiannavy.gov.in.":
    "अग्निवीर एसएसआर नौसेना की चार वर्षीय भर्ती के लिए विज्ञान सहित बारहवीं प्रवेश है। ऊँचाई, दृष्टि और भौतिकी-गणित का प्रतिशत छूटा तो अयोग्य। आवेदन केवल joinindiannavy.gov.in पर।",
  "AFCAT selects flying, technical, and ground-duty officers. The technical branch needs an engineering degree; flying and ground duty follow the streams named in the notification. File the form at afcat.cdac.in.":
    "एएफसीएटी फ्लाइंग, तकनीकी और ग्राउंड ड्यूटी अधिकारी चुनता है। तकनीकी शाखा को इंजीनियरिंग डिग्री चाहिए। फॉर्म afcat.cdac.in पर भरें।",
  "MTS is the 10th-pass cadre for central offices. Havaldar posts in CBIC and CBN add a physical test. The form is on the SSC website.":
    "एमटीएस केंद्रीय कार्यालयों का दसवीं पास संवर्ग है। सीबीआईसी और सीबीएन के हवलदार पदों में शारीरिक परीक्षा जुड़ती है। फॉर्म एसएससी वेबसाइट पर है।",
  "SSC has published the final result and marks for Stenographer Grade C and D 2025. The list is roll-number wise. Download it from ssc.gov.in and match your roll number; this desk does not reprint the merit list.":
    "एसएससी ने आशुलिपिक ग्रेड सी और डी 2025 का अंतिम परिणाम और अंक जारी किए हैं। सूची रोल नंबर के अनुसार है। ssc.gov.in से डाउनलोड करें। यह डेस्क मेरिट सूची दोबारा नहीं छापता।",
  "The CHSL 2025 final result, with cut-off, is on the SSC site. Tier II qualifying status and post allocation are in separate annexures. Read the annexure that matches your post preference.":
    "सीएचएसएल 2025 का अंतिम परिणाम और कट-ऑफ एसएससी साइट पर है। टियर II योग्यता और पद आवंटन अलग अनुलग्नक में हैं। अपनी पसंद वाले पद का अनुलग्नक पढ़ें।",
  "SSC has declared the MTS and Havaldar final result. Havaldar candidates still need the physical standard already tested; the result PDF does not replace that record.":
    "एसएससी ने एमटीएस और हवलदार का अंतिम परिणाम घोषित किया है। हवलदार अभ्यर्थियों का शारीरिक मानक पहले जाँचा गया रहता है। परिणाम पीडीएफ उस रिकॉर्ड की जगह नहीं लेता।",
  "Railway Recruitment Boards have released the CBT-II result for Assistant Loco Pilot under CEN 01/2025. The second-stage exam was held on 28 July 2026. The form itself closed on 19 May 2025. Open the RRB that accepted your application and match the list by roll number. A PDF on one zone is not the result for another zone.":
    "रेलवे भर्ती बोर्डों ने सीईएन 01/2025 के सहायक लोको पायलट का सीबीटी-II परिणाम जारी किया है। द्वितीय चरण की परीक्षा 28 जुलाई 2026 को हुई थी। फॉर्म 19 मई 2025 को बंद हो चुका था। जिस आरआरबी ने आवेदन लिया, वहीं रोल नंबर मिलाएँ। एक जोन की पीडीएफ दूसरे जोन का परिणाम नहीं है।",
  "UPPSC has published the LT Grade mains result for the assistant teacher recruitment. Subject-wise lists are long. Search by roll number on the PDF from uppsc.up.nic.in.":
    "यूपीपीएससी ने सहायक शिक्षक भर्ती का एलटी ग्रेड मुख्य परिणाम जारी किया है। विषयवार सूचियाँ लंबी हैं। uppsc.up.nic.in की पीडीएफ में रोल नंबर खोजें।",
  "IBPS has opened the RRB office assistant prelims score link. State-wise cut-offs differ. Log in with your registration number on ibps.in.":
    "आईबीपीएस ने आरआरबी कार्यालय सहायक प्रारंभिक स्कोर लिंक खोला है। राज्यवार कट-ऑफ अलग हैं। ibps.in पर पंजीकरण संख्या से लॉग इन करें।",
  "The 70th combined prelims result is the gateway to the main exam. Only roll numbers on the BPSC PDF are through. Cut-off by category is printed with the list.":
    "70वीं संयुक्त प्रारंभिक परिणाम मुख्य परीक्षा का प्रवेश है। केवल बीपीएससी पीडीएफ के रोल नंबर उत्तीर्ण हैं। वर्गवार कट-ऑफ सूची के साथ छपा है।",
  "RPSC has released the sub-inspector written result. Physical tests, where still pending, are scheduled by the police department named in the result notice.":
    "आरपीएससी ने उप निरीक्षक लिखित परिणाम जारी किया है। जहाँ शारीरिक परीक्षा बाकी है, उसे परिणाम सूचना में लिखे पुलिस विभाग की तिथि पर होना है।",
  "The forest service main result shortlists candidates for the interview. Science and forestry optional papers are listed separately.":
    "वन सेवा मुख्य परिणाम साक्षात्कार के लिए शॉर्टलिस्ट करता है। विज्ञान और वानिकी वैकल्पिक पत्र अलग सूची में हैं।",
  "The CDS II written result names candidates called to the SSB. IMA, INA, AFA, and OTA lists are separate. Your written roll number must appear on the right list.":
    "सीडीएस II लिखित परिणाम एसएसबी के लिए बुलाए अभ्यर्थियों के नाम देता है। आईएमए, आईएनए, एएफए और ओटीए की सूचियाँ अलग हैं। रोल नंबर सही सूची में होना चाहिए।",
  "The Navy has published the SSR written result for the current intake. Shortlisted candidates get a PFT city. The list lives on joinindiannavy.gov.in.":
    "नौसेना ने इस भर्ती का एसएसआर लिखित परिणाम जारी किया है। शॉर्टलिस्ट अभ्यर्थियों को पीएफटी शहर मिलता है। सूची joinindiannavy.gov.in पर है।",
  "The CGL Tier I hall ticket is on the SSC candidate portal. Carry the photo ID you named in the form. A city intimation slip is not the admit card.":
    "सीजीएल टियर I हॉल टिकट एसएससी अभ्यर्थी पोर्टल पर है। फॉर्म में लिखा फोटो पहचान पत्र ले जाएँ। सिटी स्लिप एडमिट कार्ड नहीं है।",
  "IBPS has opened the clerk prelims call letter. The photo and signature on the card must match the form. Handwritten notes are not allowed into the lab.":
    "आईबीपीएस ने लिपिक प्रारंभिक कॉल लेटर खोला है। कार्ड का फोटो और हस्ताक्षर फॉर्म से मिलें। प्रयोगशाला में हस्तलिखित नोट नहीं ले जा सकते।",
  "Technician CBT admit cards are issued by the RRB you applied to. Download from that region. ITI trade and CEN number are printed on the card — check both.":
    "टेक्निशियन सीबीटी एडमिट कार्ड उसी आरआरबी से आता है जहाँ आवेदन किया। उसी क्षेत्र से डाउनलोड करें। कार्ड पर आईटीआई ट्रेड और सीईएन नंबर दोनों जाँचें।",
  "The RO / ARO hall ticket is on the UPPSC portal. The exam city is not changed by email. Ignore any message that asks you to pay for a centre change.":
    "आरओ / एआरओ हॉल टिकट यूपीपीएससी पोर्टल पर है। परीक्षा शहर ईमेल से नहीं बदलता। केंद्र बदलने के नाम पर पैसे माँगने वाला संदेश छोड़ दें।",
  "Download the AFCAT admit card from afcat.cdac.in. The exam is online. Reporting time is earlier than the test time printed in bold.":
    "एएफसीएटी एडमिट कार्ड afcat.cdac.in से डाउनलोड करें। परीक्षा ऑनलाइन है। रिपोर्टिंग समय मोटे अक्षरों वाले परीक्षा समय से पहले है।",
  "The CAPF AC written admit card is issued on upsconline.gov.in. Physical tests come after the written result, not on this card.":
    "सीएपीएफ एसी लिखित एडमिट कार्ड upsconline.gov.in पर आता है। शारीरिक परीक्षा लिखित परिणाम के बाद है, इस कार्ड पर नहीं।",
  "BPSC has indicated that the TRE 4.0 exam date will be announced after the application window. This is a date notice, not a hall ticket. Do not download admit cards from unofficial PDFs.":
    "बीपीएससी ने बताया है कि टीआरई 4.0 की परीक्षा तिथि आवेदन खिड़की के बाद घोषित होगी। यह तिथि सूचना है, हॉल टिकट नहीं। अनौपचारिक पीडीएफ से एडमिट कार्ड न लें।",
  "The physical test call letter for GD Constable is separate from the written admit card. Carry both if your centre asks. Height and chest rules are in the CEN.":
    "जीडी कांस्टेबल का शारीरिक परीक्षा कॉल लेटर लिखित एडमिट कार्ड से अलग है। केंद्र माँगे तो दोनों ले जाएँ। ऊँचाई और छाती के नियम सीईएन में हैं।",
  "School lecturer admit cards are subject-wise. Download the card for the subject you opted. A mismatch of subject code is a reason centres turn candidates away.":
    "स्कूल लेक्चरर एडमिट कार्ड विषय के अनुसार हैं। जिस विषय को चुना, वही कार्ड लें। विषय कोड अलग हो तो केंद्र मोड़ सकता है।",
  "The state service prelims card is on the MPPSC site. Two papers are held the same day. Reach the centre with the photo ID named in the application.":
    "राज्य सेवा प्रारंभिक कार्ड एमपीपीएससी साइट पर है। एक ही दिन दो पत्र होते हैं। आवेदन वाला फोटो पहचान पत्र लेकर केंद्र पहुँचें।",
  "Matric recruit admit cards list the written exam city. The physical test is a later call. Download only from the Navy site.":
    "मैट्रिक भर्ती एडमिट कार्ड लिखित परीक्षा का शहर बताता है। शारीरिक परीक्षा बाद की पुकार है। केवल नौसेना साइट से डाउनलोड करें।",
  "Navik stage-I admit cards name the exam city and the shift. Stage II, the physical test, is not on this card.":
    "नाविक चरण-I एडमिट कार्ड शहर और पाली बताता है। चरण II, शारीरिक परीक्षा, इस कार्ड पर नहीं है।",
  "SSC has uploaded the tentative stenographer keys and response sheets. Challenges are paid and time-bound on the SSC site. A challenge filed by email is not counted.":
    "एसएससी ने आशुलिपिक की अस्थायी कुंजी और रिस्पॉन्स शीट डाली है। आपत्ति एसएससी साइट पर शुल्क और समय के साथ है। ईमेल से भेजी आपत्ति नहीं गिनी जाती।",
  "NTPC CBT keys are published region-wise with the response sheet. Objection links close on the date the RRB names. After that the final key is used for the result.":
    "एनटीपीसी सीबीटी कुंजी क्षेत्र के अनुसार रिस्पॉन्स शीट के साथ आती है। आपत्ति लिंक आरआरबी की तिथि पर बंद होता है। उसके बाद अंतिम कुंजी से परिणाम बनता है।",
  "The PCS prelims key covers both general studies papers. Objections need a standard source, not a coaching booklet. File them on the UPPSC objection link.":
    "पीसीएस प्रारंभिक कुंजी दोनों सामान्य अध्ययन पत्रों की है। आपत्ति के लिए मानक स्रोत चाहिए, कोचिंग पुस्तिका नहीं। यूपीपीएससी आपत्ति लिंक पर भरें।",
  "SET keys are published paper-wise. Eligibility for assistant professor recruitment depends on the final key and the cut-off, not on a raw score you total yourself.":
    "सेट कुंजी पत्रवार आती है। सहायक आचार्य भर्ती की पात्रता अंतिम कुंजी और कट-ऑफ पर है, खुद जोड़े कच्चे अंक पर नहीं।",
  "When BPSC uploads a TRE key, objections are taken online for a few days. This desk records that a key cycle is part of the recruitment. Use only the link on bpsc.bihar.gov.in.":
    "जब बीपीएससी टीआरई कुंजी डालता है, कुछ दिनों तक ऑनलाइन आपत्ति ली जाती है। केवल bpsc.bihar.gov.in का लिंक उपयोग करें।",
  "CHSL Tier I is English, general intelligence, quantitative aptitude, and general awareness. Tier II adds a skill test for data entry and typing posts. The official scheme of examination is the one SSC prints with the notice, and it overrides any coaching table.":
    "सीएचएसएल टियर I में अंग्रेजी, सामान्य बुद्धि, मात्रात्मक अभिरुचि और सामान्य जागरूकता है। टियर II में डेटा एंट्री और टाइपिंग पदों की कौशल परीक्षा जुड़ती है। आधिकारिक योजना वही है जो एसएससी सूचना के साथ छापता है।",
  "Graduate NTPC CBT covers mathematics, general intelligence, and general awareness. A second stage and a typing or aptitude test apply only to some posts. The CEN table is the pattern that will be used.":
    "स्नातक एनटीपीसी सीबीटी में गणित, सामान्य बुद्धि और सामान्य जागरूकता है। दूसरा चरण और टाइपिंग या अभिरुचि परीक्षा कुछ पदों पर ही है। पैटर्न सीईएन तालिका है।",
  "TRE papers differ by the class you are applying to teach. Language, general studies, and the subject paper are not the same weight for classes 1–5 and classes 11–12. Download the subject-wise syllabus from BPSC.":
    "टीआरई पत्र उस कक्षा पर निर्भर हैं जिसे पढ़ाना है। कक्षा 1–5 और 11–12 में भाषा, सामान्य अध्ययन और विषय पत्र का भार एक नहीं। विषयवार पाठ्यक्रम बीपीएससी से लें।",
  "Prelims is English, numerical ability, and reasoning. Mains adds general and financial awareness. There is no interview for clerk. Section times are fixed.":
    "प्रारंभिक में अंग्रेजी, संख्यात्मक क्षमता और तर्क है। मुख्य में सामान्य और वित्तीय जागरूकता जुड़ती है। लिपिक का साक्षात्कार नहीं है। खंड का समय तय है।",
  "NDA has two papers: Mathematics, and General Ability (English plus general knowledge). Navy and Air Force candidates still sit the same written papers; the 12th subject rule is an eligibility rule, not a third paper.":
    "एनडीए के दो पत्र हैं: गणित, और सामान्य योग्यता (अंग्रेजी तथा सामान्य ज्ञान)। नौसेना और वायु सेना के अभ्यर्थी भी वही लिखित पत्र देते हैं। बारहवीं का विषय पात्रता है, तीसरा पत्र नहीं।",
  "NTA opens a short correction window for CUET undergraduate applications. Photograph, subject choices, and category claims that the window allows can be edited. Fields it locks cannot be changed by email.":
    "एनटीए सीयूईटी स्नातक आवेदन के लिए छोटी सुधार खिड़की खोलता है। जो फ़ोटो, विषय और वर्ग दावा खिड़की खोले, वही बदल सकते हैं। बंद फ़ील्ड ईमेल से नहीं बदलते।",
  "NORCET recruits nursing officers for AIIMS and participating institutes. The circulated vacancy is about 2,216. Eligibility is B.Sc. Nursing or the equivalent the notice names. Apply on the AIIMS exams portal.":
    "नॉर्सेट एम्स और भागीदार संस्थानों के नर्सिंग अधिकारी भरता है। घोषित रिक्ति लगभग 2,216 है। पात्रता बी.एससी. नर्सिंग या सूचना में लिखा समकक्ष है। आवेदन एम्स परीक्षा पोर्टल पर करें।",
  "Qualifying candidates can download the CTET eligibility certificate from ctet.nic.in. The certificate is proof of eligibility to apply for teaching posts. It is not itself an appointment.":
    "उत्तीर्ण अभ्यर्थी ctet.nic.in से सीटीईटी पात्रता प्रमाण पत्र डाउनलोड कर सकते हैं। यह शिक्षक पद के आवेदन की पात्रता है, नियुक्ति नहीं।",
  "NTA has opened the UGC NET e-certificate for the June cycle. JRF and assistant-professor eligibility are marked on the certificate. Download it from the NTA portal.":
    "एनटीए ने जून चक्र का यूजीसी नेट ई-प्रमाण पत्र खोला है। जेआरएफ और सहायक आचार्य पात्रता प्रमाण पत्र पर अंकित है। एनटीए पोर्टल से डाउनलोड करें।",
  "SSC publishes final marks for CGL after the result. The marks page is login-based. A screenshot from a coaching site is not the official scorecard.":
    "एसएससी परिणाम के बाद सीजीएल के अंतिम अंक जारी करता है। अंक पृष्ठ लॉगिन वाला है। कोचिंग साइट का स्क्रीनशॉट आधिकारिक स्कोरकार्ड नहीं है।",
  "SSC’s calendar lists tentative dates for CGL, CHSL, MTS, JE, and other exams. Dates slip. The notice for each exam, not the calendar grid, is what opens the form.":
    "एसएससी कैलेंडर सीजीएल, सीएचएसएल, एमटीएस, जेई और अन्य परीक्षाओं की संभावित तिथियाँ देता है। तिथियाँ खिसकती हैं। फॉर्म प्रत्येक परीक्षा की सूचना खोलती है, कैलेंडर ग्रिड नहीं।",
  "The UPSC calendar schedules civil services, NDA, CDS, CAPF, and engineering services. It is a planning document. Each exam still gets its own notification on upsc.gov.in.":
    "यूपीएससी कैलेंडर सिविल सेवा, एनडीए, सीडीएस, सीएपीएफ और इंजीनियरिंग सेवाएँ रखता है। यह योजना दस्तावेज़ है। हर परीक्षा की अपनी अधिसूचना upsc.gov.in पर आती है।",
  "The IBPS calendar covers PO, clerk, SO, and RRB exams. Prelims and mains dates in the PDF move when a clash is announced. Check ibps.in before you book travel.":
    "आईबीपीएस कैलेंडर पीओ, लिपिक, एसओ और आरआरबी परीक्षाएँ रखता है। टकराव घोषित हो तो पीडीएफ की तिथियाँ हिलती हैं। यात्रा से पहले ibps.in देखें।",
  "Fake notices copy a board’s name, invent a fee, and send you to a private UPI ID. A real application is filed on the board’s own domain. SarkariResultaa never collects money, documents, or OTPs.":
    "नकली सूचनाएँ बोर्ड का नाम चुराकर शुल्क गढ़ती हैं और निजी यूपीआई पर भेजती हैं। असली आवेदन बोर्ड के अपने डोमेन पर होता है। SarkariResultaa कभी पैसे, दस्तावेज़ या ओटीपी नहीं लेता।",
};

Object.assign(PHRASES, TITLES, SUMMARIES, {
  "SSC GD Constable Online Form 2026": "एसएससी जीडी कांस्टेबल ऑनलाइन फॉर्म 2026",
  "SSC GD Constable, Rifleman and Sepoy Recruitment 2026": "एसएससी जीडी कांस्टेबल, राइफलमैन और सिपाही भर्ती 2026",
  "SSC GD recruits constables for CAPFs, riflemen, and sepoys. The form is 10th-pass. Physical standards are in the notice. Apply only on ssc.gov.in.": "एसएससी जीडी केंद्रीय सशस्त्र बलों के कांस्टेबल, राइफलमैन और सिपाही भरता है। फॉर्म दसवीं पास है। शारीरिक मानक सूचना में हैं। आवेदन केवल ssc.gov.in पर करें।",
  "SSC CGL 2026 Online Form": "एसएससी सीजीएल 2026 ऑनलाइन फॉर्म",
  "SSC Combined Graduate Level Examination 2026": "एसएससी संयुक्त स्नातक स्तर परीक्षा 2026",
  "CGL fills inspector, assistant, and auditor posts in central departments. Tier I is a computer-based test. The vacancy moves when departments add posts. File the form on the SSC site.": "सीजीएल केंद्रीय विभागों के निरीक्षक, सहायक और लेखा परीक्षक पद भरता है। टियर I कंप्यूटर परीक्षा है। विभाग पद जोड़ें तो रिक्ति बदलती है। फॉर्म एसएससी साइट पर भरें।",
  "SSC JE Online Form 2026": "एसएससी जेई ऑनलाइन फॉर्म 2026",
  "SSC Junior Engineer Examination 2026": "एसएससी कनिष्ठ अभियंता परीक्षा 2026",
  "SSC JE covers civil, electrical, and mechanical junior engineer posts in central departments. The diploma or degree must match the branch on the notice.": "एसएससी जेई केंद्रीय विभागों के सिविल, विद्युत और यांत्रिक कनिष्ठ अभियंता पद कवर करता है। डिप्लोमा या डिग्री सूचना की शाखा से मिले।",
  "SSC Selection Post Online Form 2026": "एसएससी सिलेक्शन पोस्ट ऑनलाइन फॉर्म 2026",
  "SSC Selection Post Phase Examination 2026": "एसएससी सिलेक्शन पोस्ट चरण परीक्षा 2026",
  "Selection Post is a group of ministry vacancies at 10th, 12th, and graduate level. Each post code has its own qualification. Read the post code before you pay.": "सिलेक्शन पोस्ट मंत्रालयों की दसवीं, बारहवीं और स्नातक स्तर की रिक्तियाँ हैं। हर पोस्ट कोड की अपनी योग्यता है। शुल्क से पहले पोस्ट कोड पढ़ें।",
  "RRB Technician Online Form 2026": "आरआरबी टेक्निशियन ऑनलाइन फॉर्म 2026",
  "RRB Technician Recruitment 2026": "आरआरबी टेक्निशियन भर्ती 2026",
  "Technician posts ask for a 10th plus the ITI trade named in the CEN. Apply on the railway portal for the RRB you choose. A form on the wrong board is not transferred.": "टेक्निशियन पद दसवीं और सीईएन में लिखे आईटीआई ट्रेड माँगते हैं। जिस आरआरबी को चुनें, रेलवे पोर्टल पर आवेदन करें। गलत बोर्ड का फॉर्म नहीं जाता।",
  "RRB Level-1 Online Form 2026": "आरआरबी लेवल-1 ऑनलाइन फॉर्म 2026",
  "RRB Level-1 (Group D) Recruitment 2026": "आरआरबी लेवल-1 (ग्रुप डी) भर्ती 2026",
  "Level-1 railway posts are 10th-pass track and helper roles. The CEN splits vacancies by RRB. Physical efficiency, where required, is after the CBT.": "लेवल-1 रेलवे पद दसवीं पास ट्रैक और सहायक भूमिकाएँ हैं। सीईएन रिक्तियाँ आरआरबी के अनुसार बाँटता है। जहाँ शारीरिक दक्षता है, वह सीबीटी के बाद है।",
  "IBPS PO / MT Online Form 2026": "आईबीपीएस पीओ / एमटी ऑनलाइन फॉर्म 2026",
  "IBPS Probationary Officer CRP 2026": "आईबीपीएस प्रोबेशनरी अधिकारी सीआरपी 2026",
  "IBPS PO recruits probationary officers for participating public sector banks. Prelims, mains, and interview are all on the IBPS calendar. Apply only at ibps.in.": "आईबीपीएस पीओ भागीदार सरकारी बैंकों के प्रोबेशनरी अधिकारी भरता है। प्रारंभिक, मुख्य और साक्षात्कार आईबीपीएस कैलेंडर पर हैं। आवेदन केवल ibps.in पर।",
  "IBPS SO Online Form 2026": "आईबीपीएस एसओ ऑनलाइन फॉर्म 2026",
  "IBPS Specialist Officer CRP 2026": "आईबीपीएस विशेषज्ञ अधिकारी सीआरपी 2026",
  "Specialist officer posts cover IT, law, agriculture, HR, and marketing. Each post has its own degree. A general graduation is not enough if the post names a professional qualification.": "विशेषज्ञ अधिकारी पद आईटी, विधि, कृषि, एचआर और विपणन कवर करते हैं। हर पद की अपनी डिग्री है। पद व्यावसायिक योग्यता लिखे तो सामान्य स्नातक काफी नहीं।",
  "SBI PO Online Form 2026": "एसबीआई पीओ ऑनलाइन फॉर्म 2026",
  "SBI Probationary Officer Recruitment 2026": "एसबीआई प्रोबेशनरी अधिकारी भर्ती 2026",
  "SBI recruits probationary officers on its own career page, separate from IBPS. Prelims and mains are followed by an interview and a group exercise. Do not pay a third party for a form link.": "एसबीआई प्रोबेशनरी अधिकारी अपने करियर पृष्ठ पर भरता है, आईबीपीएस से अलग। प्रारंभिक और मुख्य के बाद साक्षात्कार और समूह अभ्यास है। फॉर्म लिंक के लिए किसी तीसरे को पैसे न दें।",
  "SBI Clerk Online Form 2026": "एसबीआई लिपिक ऑनलाइन फॉर्म 2026",
  "SBI Junior Associate Recruitment 2026": "एसबीआई जूनियर एसोसिएट भर्ती 2026",
  "SBI junior associate is the clerk cadre. Local language of the state you choose is tested later. Apply on the SBI careers page.": "एसबीआई जूनियर एसोसिएट लिपिक संवर्ग है। चुने राज्य की स्थानीय भाषा बाद में जाँची जाती है। आवेदन एसबीआई करियर पृष्ठ पर करें।",
  "UPSC CDS I 2027 Online Form": "यूपीएससी सीडीएस I 2027 ऑनलाइन फॉर्म",
  "UPSC Combined Defence Services Examination (I) 2027": "यूपीएससी संयुक्त रक्षा सेवा परीक्षा (I) 2027",
  "CDS I selects officers for IMA, INA, AFA, and OTA. The degree rule differs by academy. Unmarried candidates file only at upsconline.gov.in.": "सीडीएस I आईएमए, आईएनए, एएफए और ओटीए के अधिकारी चुनता है। डिग्री नियम अकादमी पर निर्भर है। अविवाहित अभ्यर्थी केवल upsconline.gov.in पर भरें।",
  "UPSC Civil Services 2027 Online Form": "यूपीएससी सिविल सेवा 2027 ऑनलाइन फॉर्म",
  "UPSC Civil Services Preliminary Examination 2027": "यूपीएससी सिविल सेवा प्रारंभिक परीक्षा 2027",
  "The civil services prelims is the screening test for IAS, IPS, IFS, and other Group A and B services. Attempt limits and the degree rule are in the notification. Apply on the UPSC portal.": "सिविल सेवा प्रारंभिक आईएएस, आईपीएस, आईएफएस और अन्य ग्रुप ए और बी सेवाओं की छँटनी परीक्षा है। प्रयास सीमा और डिग्री नियम अधिसूचना में हैं। आवेदन यूपीएससी पोर्टल पर करें।",
  "RPSC RAS Online Form 2026": "आरपीएससी आरएएस ऑनलाइन फॉर्म 2026",
  "RPSC State and Subordinate Services Examination 2026": "आरपीएससी राज्य और अधीनस्थ सेवा परीक्षा 2026",
  "RAS is the Rajasthan state service exam. Prelims is a screening test. Domicile and reservation claims must match the RPSC advertisement.": "आरएएस राजस्थान राज्य सेवा परीक्षा है। प्रारंभिक छँटनी है। निवास और आरक्षण दावा आरपीएससी विज्ञापन से मिले।",
  "DSSSB TGT Online Form 2026": "डीएसएसएसबी टीजीटी ऑनलाइन फॉर्म 2026",
  "DSSSB Trained Graduate Teacher Recruitment 2026": "डीएसएसएसबी प्रशिक्षित स्नातक शिक्षक भर्ती 2026",
  "DSSSB recruits trained graduate teachers for Delhi schools. The subject degree and B.Ed must match the post code. One-time registration on the DSSSB portal is separate from this form.": "डीएसएसएसबी दिल्ली स्कूलों के प्रशिक्षित स्नातक शिक्षक भरता है। विषय डिग्री और बी.एड पोस्ट कोड से मिलें। पोर्टल पर एक बार का पंजीकरण इस फॉर्म से अलग है।",
  "KVS PRT Online Form 2026": "केवीएस पीआरटी ऑनलाइन फॉर्म 2026",
  "Kendriya Vidyalaya Primary Teacher Recruitment 2026": "केंद्रीय विद्यालय प्राथमिक शिक्षक भर्ती 2026",
  "KVS primary teacher posts need the teacher-eligibility route printed in the notice, usually CTET Paper I plus the training diploma. The form is on the KVS site.": "केवीएस प्राथमिक शिक्षक पद सूचना वाला शिक्षक-पात्रता मार्ग माँगते हैं, आमतौर पर सीटीईटी पेपर I और प्रशिक्षण डिप्लोमा। फॉर्म केवीएस साइट पर है।",
  "NVS TGT Online Form 2026": "एनवीएस टीजीटी ऑनलाइन फॉर्म 2026",
  "Navodaya Vidyalaya Trained Graduate Teacher Recruitment 2026": "नवोदय विद्यालय प्रशिक्षित स्नातक शिक्षक भर्ती 2026",
  "NVS trained graduate teachers work in Jawahar Navodaya Vidyalayas. Subject, B.Ed, and CTET conditions are post-wise. Apply on the Navodaya site.": "एनवीएस प्रशिक्षित स्नातक शिक्षक जवाहर नवोदय विद्यालयों में काम करते हैं। विषय, बी.एड और सीटीईटी शर्तें पद के अनुसार हैं। आवेदन नवोदय साइट पर करें।",
  "FCI Category III Online Form 2026": "एफसीआई श्रेणी III ऑनलाइन फॉर्म 2026",
  "Food Corporation of India Category III Recruitment 2026": "भारतीय खाद्य निगम श्रेणी III भर्ती 2026",
  "FCI Category III covers junior engineer, assistant grade, and typist posts. The degree or diploma depends on the post. The form is on fci.gov.in.": "एफसीआई श्रेणी III में कनिष्ठ अभियंता, सहायक ग्रेड और टाइपिस्ट पद हैं। डिग्री या डिप्लोमा पद पर निर्भर है। फॉर्म fci.gov.in पर है।",
  "India Post GDS Online Form 2026": "इंडिया पोस्ट जीडीएस ऑनलाइन फॉर्म 2026",
  "Gramin Dak Sevak Recruitment 2026": "ग्रामीण डाक सेवक भर्ती 2026",
  "GDS posts are 10th-pass and tied to a particular post office. You must meet the local residence and cycling rules in the notification. Apply on the India Post GDS portal.": "जीडीएस पद दसवीं पास हैं और एक डाकघर से जुड़े हैं। सूचना का स्थानीय निवास और साइकिल नियम पूरा होना चाहिए। आवेदन इंडिया पोस्ट जीडीएस पोर्टल पर करें।",
  "ESIC UDC and Stenographer Online Form 2026": "ईएसआईसी यूडीसी और आशुलिपिक ऑनलाइन फॉर्म 2026",
  "ESIC Upper Division Clerk and Stenographer Recruitment 2026": "ईएसआईसी उच्च श्रेणी लिपिक और आशुलिपिक भर्ती 2026",
  "ESIC UDC is a 12th-level clerical post. Stenographer adds a shorthand skill test. State-wise vacancies are in the advertisement on esic.gov.in.": "ईएसआईसी यूडीसी बारहवीं स्तर का लिपिक पद है। आशुलिपिक में शॉर्टहैंड कौशल परीक्षा जुड़ती है। राज्यवार रिक्ति esic.gov.in के विज्ञापन में है।",
  "EPFO Social Security Assistant Online Form 2026": "ईपीएफओ सामाजिक सुरक्षा सहायक ऑनलाइन फॉर्म 2026",
  "EPFO Social Security Assistant Recruitment 2026": "ईपीएफओ सामाजिक सुरक्षा सहायक भर्ती 2026",
  "EPFO social security assistant is a graduate clerical post. A typing or computer skill test follows the written papers. Apply on the EPFO site.": "ईपीएफओ सामाजिक सुरक्षा सहायक स्नातक लिपिक पद है। लिखित पत्रों के बाद टाइपिंग या कंप्यूटर कौशल परीक्षा है। आवेदन ईपीएफओ साइट पर करें।",
  "GD Constable": "जीडी कांस्टेबल",
  "Junior engineer": "कनिष्ठ अभियंता",
  "Post codes": "पोस्ट कोड",
  Technician: "टेक्निशियन",
  "Level-1": "लेवल-1",
  "Probationary officer": "प्रोबेशनरी अधिकारी",
  "Specialist posts": "विशेषज्ञ पद",
  PO: "पीओ",
  "Junior associate": "जूनियर एसोसिएट",
  "IMA / OTA": "आईएमए / ओटीए",
  "INA / AFA": "आईएनए / एएफए",
  "All services": "सभी सेवाएँ",
  "State services": "राज्य सेवाएँ",
  TGT: "टीजीटी",
  PRT: "पीआरटी",
  "Category III": "श्रेणी III",
  GDS: "जीडीएस",
  UDC: "यूडीसी",
  Stenographer: "आशुलिपिक",
  SSA: "एसएसए",
  "Paper I": "पत्र I",
  "Paper II": "पत्र II",
  "Interview and group exercise": "साक्षात्कार और समूह अभ्यास",
  "Local language test": "स्थानीय भाषा परीक्षा",
  "Merit on 10th marks": "दसवीं के अंकों पर मेरिट",
  "Skill test for stenographer": "आशुलिपिक की कौशल परीक्षा",
  "Skill test where required": "जहाँ आवश्यक हो, कौशल परीक्षा",
  "Physical efficiency test": "शारीरिक दक्षता परीक्षा",
  "PET / PST": "पीईटी / पीएसटी",
  "10th pass from a recognised board.": "मान्य बोर्ड से दसवीं पास।",
  "Diploma or degree in the notified engineering branch.": "अधिसूचित इंजीनियरिंग शाखा में डिप्लोमा या डिग्री।",
  "10th, 12th, or graduation, as printed against that post code.": "उस पोस्ट कोड के सामने छपा दसवीं, बारहवीं या स्नातक।",
  "10th with ITI in the trade printed for that post.": "उस पद के लिए छपे ट्रेड में दसवीं सहित आईटीआई।",
  "10th pass, or ITI where the CEN substitutes it, from a recognised board.": "मान्य बोर्ड से दसवीं पास, या जहाँ सीईएन आईटीआई माने।",
  "Graduation in any discipline from a recognised university.": "मान्य विश्वविद्यालय से किसी भी विषय में स्नातक।",
  "The degree or professional qualification printed for that post.": "उस पद के लिए छपी डिग्री या व्यावसायिक योग्यता।",
  "Graduation in any discipline. Final-year rules, if any, are in the SBI advertisement.": "किसी भी विषय में स्नातक। अंतिम वर्ष का नियम हो तो एसबीआई विज्ञापन में है।",
  "Graduation in any discipline. Proficiency in the local language is checked after the mains.": "किसी भी विषय में स्नातक। मुख्य परीक्षा के बाद स्थानीय भाषा जाँची जाती है।",
  "A bachelor’s degree, as the notice states for that academy.": "स्नातक डिग्री, जैसा उस अकादमी के लिए सूचना कहे।",
  "A degree with Physics and Mathematics, or the engineering route the notice allows.": "भौतिकी और गणित सहित डिग्री, या सूचना वाला इंजीनियरिंग मार्ग।",
  "A bachelor’s degree from a recognised university. Final-year students should read the appearing rule.": "मान्य विश्वविद्यालय से स्नातक। अंतिम वर्ष के छात्र उपस्थिति नियम पढ़ें।",
  "A bachelor’s degree from a recognised university. A few posts add a subject or a skill test.": "मान्य विश्वविद्यालय से स्नातक। कुछ पद विषय या कौशल परीक्षा जोड़ते हैं।",
  "Graduation from a recognised university, plus any post-wise condition in the advertisement.": "मान्य विश्वविद्यालय से स्नातक, और विज्ञापन की पदवार शर्त।",
  "Graduation in the teaching subject with B.Ed, as the post code prints it.": "पोस्ट कोड के अनुसार शिक्षण विषय में स्नातक और बी.एड।",
  "Senior secondary or graduation with D.El.Ed or the equivalent, and CTET Paper I, as the notice requires.": "उच्च माध्यमिक या स्नातक, डी.एल.एड या समकक्ष, और सूचना के अनुसार सीटीईटी पेपर I।",
  "Graduation in the subject with B.Ed and CTET, where the notice names them.": "विषय में स्नातक, और जहाँ सूचना कहे बी.एड तथा सीटीईटी।",
  "Graduation, or a diploma for the engineering posts, as that post prints it.": "स्नातक, या इंजीनियरिंग पदों के लिए डिप्लोमा, जैसा पद छपे।",
  "10th pass, with the local residence condition printed for that post office.": "दसवीं पास, और उस डाकघर के लिए छपी स्थानीय निवास शर्त।",
  "12th pass from a recognised board.": "मान्य बोर्ड से बारहवीं पास।",
  "12th pass with the shorthand speed the notice names.": "बारहवीं पास और सूचना वाली शॉर्टहैंड गति।",
  "Graduation from a recognised university, plus the computer knowledge the notice describes.": "मान्य विश्वविद्यालय से स्नातक, और सूचना वाला कंप्यूटर ज्ञान।",
  "Written exam": "लिखित परीक्षा",
  "Skill test": "कौशल परीक्षा",
  Interview: "साक्षात्कार",
});

Object.assign(PHRASES, {
  "SSC CGL Tier-I Result 2026 — Out": "एसएससी सीजीएल टियर-I परिणाम 2026 — जारी",
  "SSC CGL Tier-I Result 2026": "एसएससी सीजीएल टियर-I परिणाम 2026",
  "SSC has declared the CGL Tier I result. The list is roll-number wise on ssc.gov.in. Tier II dates are in a separate notice, not on this desk.": "एसएससी ने सीजीएल टियर I परिणाम घोषित किया है। सूची रोल नंबर के अनुसार ssc.gov.in पर है। टियर II तिथियाँ अलग सूचना में हैं।",
  "SSC GD Constable Written Result 2026 — Out": "एसएससी जीडी कांस्टेबल लिखित परिणाम 2026 — जारी",
  "SSC GD Constable Written Result 2026": "एसएससी जीडी कांस्टेबल लिखित परिणाम 2026",
  "The GD Constable written result shortlists candidates for PET and PST. Height and chest rules still apply. Download the PDF from ssc.gov.in.": "जीडी कांस्टेबल लिखित परिणाम पीईटी और पीएसटी के लिए शॉर्टलिस्ट करता है। ऊँचाई और छाती के नियम लागू रहते हैं। पीडीएफ ssc.gov.in से लें।",
  "SSC JE Paper-I Result 2026 — Out": "एसएससी जेई पत्र-I परिणाम 2026 — जारी",
  "SSC Junior Engineer Paper-I Result 2026": "एसएससी कनिष्ठ अभियंता पत्र-I परिणाम 2026",
  "SSC has published the JE Paper I result. Only roll numbers on that PDF are called for Paper II. Match the engineering branch on the list.": "एसएससी ने जेई पत्र I परिणाम जारी किया है। केवल उस पीडीएफ के रोल नंबर पत्र II के लिए बुलाए गए हैं। सूची पर इंजीनियरिंग शाखा मिलाएँ।",
  "RRB NTPC CBT-1 Result 2026 — Out": "आरआरबी एनटीपीसी सीबीटी-1 परिणाम 2026 — जारी",
  "RRB NTPC CBT-1 Result 2026": "आरआरबी एनटीपीसी सीबीटी-1 परिणाम 2026",
  "Regional RRBs have released NTPC CBT-1 results. Open the RRB that accepted your form. A list from another zone is not yours.": "क्षेत्रीय आरआरबी ने एनटीपीसी सीबीटी-1 परिणाम जारी किए हैं। जिस आरआरबी ने फॉर्म लिया वही खोलें। दूसरे जोन की सूची आपकी नहीं।",
  "RRB Level-1 CBT Result 2026 — Out": "आरआरबी लेवल-1 सीबीटी परिणाम 2026 — जारी",
  "RRB Level-1 CBT Result 2026": "आरआरबी लेवल-1 सीबीटी परिणाम 2026",
  "The Level-1 CBT result is published by each RRB. Shortlisted candidates still have the physical efficiency test. Check the CEN number on the PDF.": "लेवल-1 सीबीटी परिणाम हर आरआरबी जारी करता है। शॉर्टलिस्ट अभ्यर्थियों की शारीरिक दक्षता परीक्षा बाकी है। पीडीएफ पर सीईएन नंबर देखें।",
  "IBPS PO Prelims Result 2026 — Out": "आईबीपीएस पीओ प्रारंभिक परिणाम 2026 — जारी",
  "IBPS Probationary Officer Prelims Result 2026": "आईबीपीएस प्रोबेशनरी अधिकारी प्रारंभिक परिणाम 2026",
  "IBPS has opened the PO prelims score link. State-wise cut-offs differ. Log in with your registration number on ibps.in.": "आईबीपीएस ने पीओ प्रारंभिक स्कोर लिंक खोला है। राज्यवार कट-ऑफ अलग हैं। ibps.in पर पंजीकरण संख्या से लॉग इन करें।",
  "IBPS SO Prelims Result 2026 — Out": "आईबीपीएस एसओ प्रारंभिक परिणाम 2026 — जारी",
  "IBPS Specialist Officer Prelims Result 2026": "आईबीपीएस विशेषज्ञ अधिकारी प्रारंभिक परिणाम 2026",
  "The SO prelims result is post-wise. An IT score is not the law or agriculture list. Log in on ibps.in and read the post name on the scorecard.": "एसओ प्रारंभिक परिणाम पदवार है। आईटी का स्कोर विधि या कृषि सूची नहीं है। ibps.in पर लॉग इन करके स्कोरकार्ड का पद पढ़ें।",
  "SBI PO Prelims Result 2026 — Out": "एसबीआई पीओ प्रारंभिक परिणाम 2026 — जारी",
  "SBI Probationary Officer Prelims Result 2026": "एसबीआई प्रोबेशनरी अधिकारी प्रारंभिक परिणाम 2026",
  "SBI has published the PO prelims result on its career page. This is not the IBPS PO list. Log in with the registration number from the SBI form.": "एसबीआई ने पीओ प्रारंभिक परिणाम अपने करियर पृष्ठ पर जारी किया है। यह आईबीपीएस पीओ सूची नहीं है। एसबीआई फॉर्म की पंजीकरण संख्या से लॉग इन करें।",
  "SBI Clerk Mains Result 2026 — Out": "एसबीआई लिपिक मुख्य परिणाम 2026 — जारी",
  "SBI Junior Associate Mains Result 2026": "एसबीआई जूनियर एसोसिएट मुख्य परिणाम 2026",
  "The junior associate mains result is state-wise. A local-language test may still follow. Download the score from the SBI careers page.": "जूनियर एसोसिएट मुख्य परिणाम राज्यवार है। स्थानीय भाषा परीक्षा बाद में हो सकती है। स्कोर एसबीआई करियर पृष्ठ से लें।",
  "UPSC CSE Prelims Result 2026 — Out": "यूपीएससी सीएसई प्रारंभिक परिणाम 2026 — जारी",
  "UPSC Civil Services Preliminary Result 2026": "यूपीएससी सिविल सेवा प्रारंभिक परिणाम 2026",
  "The civil services prelims result names candidates for the main exam. Only roll numbers on the UPSC PDF are through. Cut-off is printed with the list.": "सिविल सेवा प्रारंभिक परिणाम मुख्य परीक्षा के अभ्यर्थी बताता है। केवल यूपीएससी पीडीएफ के रोल नंबर उत्तीर्ण हैं। कट-ऑफ सूची के साथ छपा है।",
  "UPSC CAPF Written Result 2026 — Out": "यूपीएससी सीएपीएफ लिखित परिणाम 2026 — जारी",
  "UPSC CAPF Assistant Commandant Written Result 2026": "यूपीएससी सीएपीएफ सहायक कमांडेंट लिखित परिणाम 2026",
  "The CAPF written result calls candidates to the physical test. The admit card for the written exam is not this list. Read the PDF on upsc.gov.in.": "सीएपीएफ लिखित परिणाम शारीरिक परीक्षा के लिए बुलाता है। लिखित परीक्षा का एडमिट कार्ड यह सूची नहीं है। पीडीएफ upsc.gov.in पर पढ़ें।",
  "BPSC TRE Result 2026 — Out": "बीपीएससी टीआरई परिणाम 2026 — जारी",
  "BPSC School Teacher TRE Result 2026": "बीपीएससी स्कूल शिक्षक टीआरई परिणाम 2026",
  "BPSC has published a TRE result list. Subject and class are separate PDFs. Search your roll number on bpsc.bihar.gov.in.": "बीपीएससी ने टीआरई परिणाम सूची जारी की है। विषय और कक्षा की पीडीएफ अलग हैं। रोल नंबर bpsc.bihar.gov.in पर खोजें।",
  "UPPSC PCS Prelims Result 2026 — Out": "यूपीपीएससी पीसीएस प्रारंभिक परिणाम 2026 — जारी",
  "UPPSC Combined State Prelims Result 2026": "यूपीपीएससी संयुक्त राज्य प्रारंभिक परिणाम 2026",
  "The PCS prelims result is the gateway to the main exam. Only roll numbers on the UPPSC PDF qualify. Download it from uppsc.up.nic.in.": "पीसीएस प्रारंभिक परिणाम मुख्य परीक्षा का प्रवेश है। केवल यूपीपीएससी पीडीएफ के रोल नंबर योग्य हैं। uppsc.up.nic.in से डाउनलोड करें।",
  "RPSC RAS Prelims Result 2026 — Out": "आरपीएससी आरएएस प्रारंभिक परिणाम 2026 — जारी",
  "RPSC State Services Prelims Result 2026": "आरपीएससी राज्य सेवा प्रारंभिक परिणाम 2026",
  "RPSC has released the RAS prelims result. The mains form, if opened, is a separate notice. Match your roll number on the RPSC PDF.": "आरपीएससी ने आरएएस प्रारंभिक परिणाम जारी किया है। मुख्य फॉर्म खुले तो वह अलग सूचना है। रोल नंबर आरपीएससी पीडीएफ पर मिलाएँ।",
  "MPPSC State Service Prelims Result 2026 — Out": "एमपीपीएससी राज्य सेवा प्रारंभिक परिणाम 2026 — जारी",
  "MPPSC State Service Prelims Result 2026": "एमपीपीएससी राज्य सेवा प्रारंभिक परिणाम 2026",
  "The state service prelims result shortlists candidates for the mains. Paper-wise marks, if published, are a later link. Use mppsc.mp.gov.in.": "राज्य सेवा प्रारंभिक परिणाम मुख्य परीक्षा के लिए शॉर्टलिस्ट करता है। पत्रवार अंक बाद के लिंक पर हो सकते हैं। mppsc.mp.gov.in उपयोग करें।",
  "DSSSB TGT Result 2026 — Out": "डीएसएसएसबी टीजीटी परिणाम 2026 — जारी",
  "DSSSB Trained Graduate Teacher Result 2026": "डीएसएसएसबी प्रशिक्षित स्नातक शिक्षक परिणाम 2026",
  "DSSSB TGT results are post-code wise. A result for one subject is not valid for another. Open the PDF that matches your post code on dsssbonline.nic.in.": "डीएसएसएसबी टीजीटी परिणाम पोस्ट कोड के अनुसार हैं। एक विषय का परिणाम दूसरे के लिए मान्य नहीं। अपना पोस्ट कोड वाला पीडीएफ dsssbonline.nic.in पर खोलें।",
  "KVS PRT Result 2026 — Out": "केवीएस पीआरटी परिणाम 2026 — जारी",
  "Kendriya Vidyalaya Primary Teacher Result 2026": "केंद्रीय विद्यालय प्राथमिक शिक्षक परिणाम 2026",
  "KVS has published the primary teacher result. Interview or document verification, if still due, is named in the same notice. Download it from the KVS site.": "केवीएस ने प्राथमिक शिक्षक परिणाम जारी किया है। साक्षात्कार या दस्तावेज़ सत्यापन बाकी हो तो उसी सूचना में है। केवीएस साइट से डाउनलोड करें।",
  "FCI Category III Result 2026 — Out": "एफसीआई श्रेणी III परिणाम 2026 — जारी",
  "FCI Category III Phase Result 2026": "एफसीआई श्रेणी III चरण परिणाम 2026",
  "The FCI Category III phase result is post-wise. A junior engineer list is not the assistant-grade list. Check the post name on the PDF at fci.gov.in.": "एफसीआई श्रेणी III चरण परिणाम पदवार है। कनिष्ठ अभियंता सूची सहायक ग्रेड सूची नहीं है। fci.gov.in की पीडीएफ पर पद का नाम देखें।",
  "ESIC UDC Result 2026 — Out": "ईएसआईसी यूडीसी परिणाम 2026 — जारी",
  "ESIC Upper Division Clerk Result 2026": "ईएसआईसी उच्च श्रेणी लिपिक परिणाम 2026",
  "ESIC has declared the UDC result. Stenographer candidates use a different list. State and region are printed on the score link at esic.gov.in.": "ईएसआईसी ने यूडीसी परिणाम घोषित किया है। आशुलिपिक अभ्यर्थी अलग सूची देखें। राज्य और क्षेत्र esic.gov.in के स्कोर लिंक पर छपे हैं।",
  "SSC MTS Admit Card 2026": "एसएससी एमटीएस एडमिट कार्ड 2026",
  "SSC MTS and Havaldar Admit Card 2026": "एसएससी एमटीएस और हवलदार एडमिट कार्ड 2026",
  "The MTS hall ticket is on the SSC portal. Havaldar candidates should also read the physical-test note. A city slip is not the admit card.": "एमटीएस हॉल टिकट एसएससी पोर्टल पर है। हवलदार अभ्यर्थी शारीरिक परीक्षा नोट भी पढ़ें। सिटी स्लिप एडमिट कार्ड नहीं है।",
  "SSC CHSL Tier-I Admit Card 2026": "एसएससी सीएचएसएल टियर-I एडमिट कार्ड 2026",
  "CHSL Tier I admit cards are live on the SSC candidate portal. Carry the photo ID named in the form. Check the shift before you leave.": "सीएचएसएल टियर I एडमिट कार्ड एसएससी अभ्यर्थी पोर्टल पर हैं। फॉर्म वाला फोटो पहचान पत्र ले जाएँ। निकलने से पहले पाली देखें।",
  "SSC JE Paper-I Admit Card 2026": "एसएससी जेई पत्र-I एडमिट कार्ड 2026",
  "SSC Junior Engineer Paper-I Admit Card 2026": "एसएससी कनिष्ठ अभियंता पत्र-I एडमिट कार्ड 2026",
  "The JE Paper I hall ticket shows your engineering discipline and shift. Download it from ssc.gov.in and match the branch.": "जेई पत्र I हॉल टिकट इंजीनियरिंग विषय और पाली दिखाता है। ssc.gov.in से डाउनलोड करके शाखा मिलाएँ।",
  "SSC Selection Post Admit Card 2026": "एसएससी सिलेक्शन पोस्ट एडमिट कार्ड 2026",
  "Selection Post admit cards are post-code wise. Download the card for the code you applied to. A mismatch of post code is a reason centres turn people away.": "सिलेक्शन पोस्ट एडमिट कार्ड पोस्ट कोड के अनुसार हैं। जिस कोड पर आवेदन किया वही कार्ड लें। पोस्ट कोड अलग हो तो केंद्र मोड़ सकता है।",
  "RRB NTPC CBT Admit Card 2026": "आरआरबी एनटीपीसी सीबीटी एडमिट कार्ड 2026",
  "NTPC CBT admit cards come from the RRB that took your form. Download from that region. Check the CEN number printed on the card.": "एनटीपीसी सीबीटी एडमिट कार्ड उसी आरआरबी से आता है जिसने फॉर्म लिया। उसी क्षेत्र से डाउनलोड करें। कार्ड पर सीईएन नंबर देखें।",
  "RRB ALP CBT Admit Card 2026": "आरआरबी एएलपी सीबीटी एडमिट कार्ड 2026",
  "RRB Assistant Loco Pilot CBT Admit Card 2026": "आरआरबी सहायक लोको पायलट सीबीटी एडमिट कार्ड 2026",
  "ALP CBT city and shift are on the admit card from your regional RRB. A card from another zone will not match your roll number.": "एएलपी सीबीटी का शहर और पाली आपके क्षेत्रीय आरआरबी के एडमिट कार्ड पर हैं। दूसरे जोन का कार्ड रोल नंबर से नहीं मिलेगा।",
  "RRB Level-1 Admit Card 2026": "आरआरबी लेवल-1 एडमिट कार्ड 2026",
  "RRB Level-1 CBT Admit Card 2026": "आरआरबी लेवल-1 सीबीटी एडमिट कार्ड 2026",
  "Level-1 hall tickets are issued by the RRB you chose. The physical test is a later call. Download only from that regional site or the railway portal.": "लेवल-1 हॉल टिकट आपके चुने आरआरबी से आता है। शारीरिक परीक्षा बाद की पुकार है। केवल उसी क्षेत्रीय साइट या रेलवे पोर्टल से डाउनलोड करें।",
  "IBPS PO Prelims Admit Card 2026": "आईबीपीएस पीओ प्रारंभिक एडमिट कार्ड 2026",
  "IBPS Probationary Officer Prelims Admit Card 2026": "आईबीपीएस प्रोबेशनरी अधिकारी प्रारंभिक एडमिट कार्ड 2026",
  "The PO prelims call letter is on ibps.in. Photograph and signature must match the form. Handwritten notes are not allowed in the lab.": "पीओ प्रारंभिक कॉल लेटर ibps.in पर है। फोटो और हस्ताक्षर फॉर्म से मिलें। प्रयोगशाला में हस्तलिखित नोट नहीं ले जा सकते।",
  "IBPS SO Prelims Admit Card 2026": "आईबीपीएस एसओ प्रारंभिक एडमिट कार्ड 2026",
  "IBPS Specialist Officer Prelims Admit Card 2026": "आईबीपीएस विशेषज्ञ अधिकारी प्रारंभिक एडमिट कार्ड 2026",
  "SO call letters name the specialist post. Check that the post on the card is the one you opted. Download it from ibps.in.": "एसओ कॉल लेटर विशेषज्ञ पद बताता है। कार्ड का पद वही हो जो आपने चुना। ibps.in से डाउनलोड करें।",
  "SBI PO Prelims Admit Card 2026": "एसबीआई पीओ प्रारंभिक एडमिट कार्ड 2026",
  "SBI Probationary Officer Prelims Admit Card 2026": "एसबीआई प्रोबेशनरी अधिकारी प्रारंभिक एडमिट कार्ड 2026",
  "The SBI PO prelims card is on the SBI careers page, not on IBPS. Carry the photo ID from the form and reach before the reporting time.": "एसबीआई पीओ प्रारंभिक कार्ड एसबीआई करियर पृष्ठ पर है, आईबीपीएस पर नहीं। फॉर्म वाला फोटो पहचान पत्र लेकर रिपोर्टिंग समय से पहले पहुँचें।",
  "SBI Clerk Prelims Admit Card 2026": "एसबीआई लिपिक प्रारंभिक एडमिट कार्ड 2026",
  "SBI Junior Associate Prelims Admit Card 2026": "एसबीआई जूनियर एसोसिएट प्रारंभिक एडमिट कार्ड 2026",
  "Junior associate prelims call letters are state-wise. Log in on the SBI careers page and check the exam city before you travel.": "जूनियर एसोसिएट प्रारंभिक कॉल लेटर राज्यवार हैं। एसबीआई करियर पृष्ठ पर लॉग इन करके यात्रा से पहले परीक्षा शहर देखें।",
  "UPSC CSE Prelims Admit Card 2026": "यूपीएससी सीएसई प्रारंभिक एडमिट कार्ड 2026",
  "UPSC Civil Services Prelims Admit Card 2026": "यूपीएससी सिविल सेवा प्रारंभिक एडमिट कार्ड 2026",
  "The civil services prelims e-admit card is on upsconline.gov.in. Two papers are the same day. Carry the photo ID printed on the card.": "सिविल सेवा प्रारंभिक ई-एडमिट कार्ड upsconline.gov.in पर है। एक ही दिन दो पत्र हैं। कार्ड वाला फोटो पहचान पत्र ले जाएँ।",
  "UPSC NDA Admit Card 2026": "यूपीएससी एनडीए एडमिट कार्ड 2026",
  "UPSC NDA and Naval Academy Admit Card 2026": "यूपीएससी एनडीए और नौसेना अकादमी एडमिट कार्ड 2026",
  "The NDA written admit card is issued on upsconline.gov.in. Mathematics and GAT are separate sessions. SSB is not on this card.": "एनडीए लिखित एडमिट कार्ड upsconline.gov.in पर आता है। गणित और जीएटी अलग सत्र हैं। एसएसबी इस कार्ड पर नहीं है।",
  "BPSC 70th CCE Mains Admit Card 2026": "बीपीएससी 70वीं सीसीई मुख्य एडमिट कार्ड 2026",
  "BPSC 70th Combined Competitive Mains Admit Card 2026": "बीपीएससी 70वीं संयुक्त प्रतियोगी मुख्य एडमिट कार्ड 2026",
  "The 70th mains hall ticket is only for roll numbers that cleared prelims. Download it from bpsc.bihar.gov.in and check the paper schedule.": "70वीं मुख्य हॉल टिकट केवल उन्हीं रोल नंबर के लिए है जो प्रारंभिक में उत्तीर्ण हुए। bpsc.bihar.gov.in से डाउनलोड करके पत्रों का कार्यक्रम देखें।",
  "UPPSC PCS Prelims Admit Card 2026": "यूपीपीएससी पीसीएस प्रारंभिक एडमिट कार्ड 2026",
  "UPPSC Combined State Prelims Admit Card 2026": "यूपीपीएससी संयुक्त राज्य प्रारंभिक एडमिट कार्ड 2026",
  "The PCS prelims card is on the UPPSC portal. The exam city is not changed by email. Ignore any message that asks you to pay for a centre change.": "पीसीएस प्रारंभिक कार्ड यूपीपीएससी पोर्टल पर है। परीक्षा शहर ईमेल से नहीं बदलता। केंद्र बदलने के नाम पर पैसे माँगने वाला संदेश छोड़ दें।",
  "RPSC RAS Prelims Admit Card 2026": "आरपीएससी आरएएस प्रारंभिक एडमिट कार्ड 2026",
  "RPSC State Services Prelims Admit Card 2026": "आरपीएससी राज्य सेवा प्रारंभिक एडमिट कार्ड 2026",
  "RAS prelims admit cards are on the RPSC site. Carry the photo ID from the application. Two sessions may fall on the same day.": "आरएएस प्रारंभिक एडमिट कार्ड आरपीएससी साइट पर हैं। आवेदन वाला फोटो पहचान पत्र ले जाएँ। दो सत्र एक ही दिन हो सकते हैं।",
  "DSSSB TGT Admit Card 2026": "डीएसएसएसबी टीजीटी एडमिट कार्ड 2026",
  "DSSSB Trained Graduate Teacher Admit Card 2026": "डीएसएसएसबी प्रशिक्षित स्नातक शिक्षक एडमिट कार्ड 2026",
  "DSSSB TGT cards are post-code wise. Download the card for the subject you opted. A wrong post code is checked at the centre.": "डीएसएसएसबी टीजीटी कार्ड पोस्ट कोड के अनुसार हैं। जिस विषय को चुना वही कार्ड लें। गलत पोस्ट कोड केंद्र पर जाँचा जाता है।",
  "KVS PRT Admit Card 2026": "केवीएस पीआरटी एडमिट कार्ड 2026",
  "Kendriya Vidyalaya Primary Teacher Admit Card 2026": "केंद्रीय विद्यालय प्राथमिक शिक्षक एडमिट कार्ड 2026",
  "The KVS primary teacher hall ticket is on the KVS site. Shift and centre address are on the first page. Carry the photo ID named in the form.": "केवीएस प्राथमिक शिक्षक हॉल टिकट केवीएस साइट पर है। पाली और केंद्र का पता पहले पृष्ठ पर है। फॉर्म वाला फोटो पहचान पत्र ले जाएँ।",
});

export function translate(lang: Lang, text: string): string {
  if (lang === "en" || !text) return text;
  const hit = PHRASES[text];
  if (hit) return hit;
  return text.replace(/\b(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b/g, (month) => MONTHS[month] ?? month);
}

export function trBadge(lang: Lang, text: string): string {
  if (lang === "en") return text;
  const days = text.match(/^(\d+) days left$/);
  if (days) return `${days[1]} दिन शेष`;
  return translate(lang, text);
}

export const UI = {
  en: {
    skip: "Skip to notices",
    kicker: "Independent exam desk",
    brand: "SarkariResultaa",
    searchLabel: "Search notices",
    searchPlaceholder: "Search boards, posts, results",
    search: "Search",
    language: "Language",
    home: "Home",
    saved: "Saved",
    tickerLabel: "Closing this week",
    tickerEmpty: "No form closes in the next 7 days.",
    footerBrand: "SarkariResultaa",
    footerBlurb: "An independent reading desk for government exams. It does not accept applications, fees, or documents.",
    onDesk: "On the desk",
    boards: "Boards",
    ageTool: "Age calculator",
    certificates: "Certificates",
    about: "About this desk",
    disclaimer: "Disclaimer",
    privacy: "Privacy",
    contact: "Contact",
    footerNote: "Confirm every date on the official board website. SarkariResultaa is not affiliated with any recruiting body.",
    statNotices: "Notices on the desk",
    statOpen: "Windows still open",
    statClosing: "Closing in 7 days",
    filter: "Filter by qualification",
    empty: "Nothing in this column for that filter.",
    viewAll: "View all",
    save: "Save notice",
    savedBtn: "Saved on this desk",
    shortDetails: "short details",
    dates: "Important dates",
    fee: "Application fee",
    pay: "Payment mode (online)",
    ageNote: "gives age relaxation as printed in its own rules.",
    total: "Total post",
    vacancy: "Vacancy details",
    postName: "Post name",
    postCount: "No. of post",
    eligibility: "Eligibility",
    also: "You may also check",
    selection: "Mode of selection",
    zones: "Check the result on your regional board",
    zoneCol: "RRB zone",
    siteCol: "Official site",
    zoneNote: "Each RRB publishes its own list. Open the board that accepted your form.",
    links: "Some useful important links",
    click: "Click here",
    questions: "Important questions",
    confirm: "Confirm every date, fee, and vacancy on the official website. This page is a reading summary, not the notification.",
    open: "Open official website",
    hot: "Open the official website before this window moves.",
    section: "Section",
    board: "Board",
    official: "Official website",
    portal: "Candidate portal",
    notices: "notices",
    allNotices: "All notices",
    found: "found",
    noMatch: "No notice matches that. Try a short board name such as SSC, RRB, BPSC, or UPSC.",
    savedLead: "Bookmarks stay in this browser. They are not an account and they are not an application.",
    opening: "Opening your bookmarks…",
    noneSaved: "Nothing saved yet. Open a notice and choose Save notice.",
    boardsLead: "Each name opens the notices on this desk. The website link leaves SarkariResultaa.",
    ageH: "Age as on a date",
    ageLead: "Boards count completed years, months, and days on the date printed in the notice. This does not decide eligibility. Relaxation for category and post is in that notice.",
    dob: "Date of birth",
    asOn: "As on",
    ageBad: "Enter a date of birth before the as-on date.",
    years: "years",
    months: "months",
    days: "days",
    missing: "Missing page",
    missingH: "This page is not on the desk",
    missingP: "The notice or section may have been mistyped. The gazette is still on the front page.",
    back: "Back to SarkariResultaa",
    d1: "SarkariResultaa is an independent reading desk. It is not a government website and it is not affiliated with SSC, UPSC, any railway board, any state commission, or any other recruiting body.",
    d2: "Dates, fees, age limits, and vacancy counts are summaries so you can decide which official notice to open. The board’s PDF is the only authority. If a figure here disagrees with that PDF, the PDF wins.",
    d3: "SarkariResultaa does not accept job applications, fees, documents, or OTPs. A page that asks you to pay SarkariResultaa is not this desk.",
    d4: "This desk is also not affiliated with other job websites, including any site that uses the name Sarkari Result.",
    p1: "Saved notices are stored in this browser only. There is no account. Clearing site data removes them.",
    p2: "Search queries stay in the page address so you can share a result list. They are not sent to a SarkariResultaa account, because there isn’t one.",
    p3: "Leaving a notice through “Click here” or “Open official website” takes you to that board. Their privacy rules apply from there.",
    c1: "This desk does not take messages, applications, or fee receipts. Writing to a random address will not file your form.",
    c2: "For a correction to your application, use the board named on the notice. The board list is on the boards page.",
    c3: "If a notice looks wrong, open the official website from the notice and read the PDF. That is the check this desk is built around.",
    ageAsOn: "Age limit as on",
    ageLimit: "Age limit",
    posts: "posts",
    seeNotice: "See the official notice",
  },
  hi: {
    skip: "सूचनाओं पर जाएँ",
    kicker: "स्वतंत्र परीक्षा डेस्क",
    brand: "SarkariResultaa",
    searchLabel: "सूचनाएँ खोजें",
    searchPlaceholder: "बोर्ड, पद, परिणाम खोजें",
    search: "खोज",
    language: "भाषा",
    home: "होम",
    saved: "सहेजे गए",
    tickerLabel: "इस सप्ताह बंद होने वाले",
    tickerEmpty: "अगले 7 दिनों में कोई फॉर्म बंद नहीं हो रहा।",
    footerBrand: "SarkariResultaa",
    footerBlurb: "सरकारी परीक्षाओं की स्वतंत्र पठन डेस्क। यह आवेदन, शुल्क या दस्तावेज़ स्वीकार नहीं करती।",
    onDesk: "डेस्क पर",
    boards: "बोर्ड",
    ageTool: "आयु कैलकुलेटर",
    certificates: "प्रमाण पत्र",
    about: "इस डेस्क के बारे में",
    disclaimer: "अस्वीकरण",
    privacy: "गोपनीयता",
    contact: "संपर्क",
    footerNote: "हर तिथि आधिकारिक बोर्ड वेबसाइट पर जाँचें। SarkariResultaa किसी भर्ती संस्था से संबद्ध नहीं है।",
    statNotices: "डेस्क पर सूचनाएँ",
    statOpen: "अभी खुली खिड़कियाँ",
    statClosing: "7 दिनों में बंद",
    filter: "योग्यता से छानें",
    empty: "इस फ़िल्टर पर इस कॉलम में कुछ नहीं।",
    viewAll: "सभी देखें",
    save: "सूचना सहेजें",
    savedBtn: "इस डेस्क पर सहेजा",
    shortDetails: "संक्षिप्त विवरण",
    dates: "महत्वपूर्ण तिथियाँ",
    fee: "आवेदन शुल्क",
    pay: "भुगतान का तरीका (ऑनलाइन)",
    ageNote: "अपने नियमों के अनुसार आयु में छूट देता है।",
    total: "कुल पद",
    vacancy: "रिक्ति विवरण",
    postName: "पद का नाम",
    postCount: "पदों की संख्या",
    eligibility: "पात्रता",
    also: "आप यह भी देख सकते हैं",
    selection: "चयन का तरीका",
    zones: "परिणाम अपने क्षेत्रीय बोर्ड पर देखें",
    zoneCol: "आरआरबी जोन",
    siteCol: "आधिकारिक साइट",
    zoneNote: "हर आरआरबी अपनी सूची जारी करता है। जिस बोर्ड ने फॉर्म लिया, वही खोलें।",
    links: "कुछ उपयोगी महत्वपूर्ण लिंक",
    click: "यहाँ क्लिक करें",
    questions: "महत्वपूर्ण प्रश्न",
    confirm: "हर तिथि, शुल्क और रिक्ति आधिकारिक वेबसाइट पर जाँचें। यह पृष्ठ पढ़ने का सार है, अधिसूचना नहीं।",
    open: "आधिकारिक वेबसाइट खोलें",
    hot: "यह खिड़की बदलने से पहले आधिकारिक वेबसाइट खोलें।",
    section: "अनुभाग",
    board: "बोर्ड",
    official: "आधिकारिक वेबसाइट",
    portal: "अभ्यर्थी पोर्टल",
    notices: "सूचनाएँ",
    allNotices: "सभी सूचनाएँ",
    found: "मिले",
    noMatch: "कोई सूचना नहीं मिली। एसएससी, आरआरबी, बीपीएससी या यूपीएससी जैसा छोटा नाम आज़माएँ।",
    savedLead: "बुकमार्क इसी ब्राउज़र में रहते हैं। यह खाता नहीं और आवेदन नहीं है।",
    opening: "आपके बुकमार्क खुल रहे हैं…",
    noneSaved: "अभी कुछ सहेजा नहीं। सूचना खोलकर सूचना सहेजें चुनें।",
    boardsLead: "हर नाम इस डेस्क की सूचनाएँ खोलता है। वेबसाइट लिंक SarkariResultaa से बाहर ले जाता है।",
    ageH: "एक तिथि पर आयु",
    ageLead: "बोर्ड सूचना में छपी तिथि पर पूरे वर्ष, महीने और दिन गिनते हैं। यह पात्रता तय नहीं करता। वर्ग और पद की छूट उसी सूचना में है।",
    dob: "जन्म तिथि",
    asOn: "इस तिथि को",
    ageBad: "जन्म तिथि, निर्धारित तिथि से पहले होनी चाहिए।",
    years: "वर्ष",
    months: "महीने",
    days: "दिन",
    missing: "पृष्ठ नहीं मिला",
    missingH: "यह पृष्ठ डेस्क पर नहीं है",
    missingP: "सूचना या अनुभाग गलत लिखा हो सकता है। SarkariResultaa पहले पृष्ठ पर है।",
    back: "SarkariResultaa पर वापस",
    d1: "SarkariResultaa एक स्वतंत्र पठन डेस्क है। यह सरकारी वेबसाइट नहीं है और एसएससी, यूपीएससी, किसी रेलवे बोर्ड, राज्य आयोग या अन्य भर्ती संस्था से संबद्ध नहीं है।",
    d2: "तिथि, शुल्क, आयु और रिक्ति सार हैं, ताकि आप तय कर सकें कौन सी आधिकारिक सूचना खोलनी है। बोर्ड की पीडीएफ ही प्रमाण है। आँकड़ा अलग हो तो पीडीएफ मानी जाएगी।",
    d3: "SarkariResultaa नौकरी आवेदन, शुल्क, दस्तावेज़ या ओटीपी स्वीकार नहीं करता। जो पृष्ठ SarkariResultaa को भुगतान माँगे, वह यह डेस्क नहीं है।",
    d4: "यह डेस्क अन्य नौकरी वेबसाइटों से भी संबद्ध नहीं है, जिनमें सरकारी परिणाम नाम वाली साइटें शामिल हैं।",
    p1: "सहेजी सूचनाएँ केवल इसी ब्राउज़र में रहती हैं। कोई खाता नहीं है। साइट डेटा साफ करने पर वे हट जाती हैं।",
    p2: "खोज पृष्ठ के पते में रहती है ताकि सूची बाँट सकें। वे किसी SarkariResultaa खाते को नहीं जातीं, क्योंकि खाता है ही नहीं।",
    p3: "“यहाँ क्लिक करें” या “आधिकारिक वेबसाइट खोलें” उस बोर्ड पर ले जाता है। वहाँ से उनके गोपनीयता नियम लागू होते हैं।",
    c1: "यह डेस्क संदेश, आवेदन या शुल्क रसीद नहीं लेती। किसी पते पर लिखने से फॉर्म नहीं भरता।",
    c2: "आवेदन सुधार के लिए सूचना पर लिखे बोर्ड का उपयोग करें। बोर्डों की सूची बोर्ड पृष्ठ पर है।",
    c3: "सूचना गलत लगे तो सूचना से आधिकारिक वेबसाइट खोलकर पीडीएफ पढ़ें। यही जाँच इस डेस्क की रीढ़ है।",
    ageAsOn: "आयु सीमा, तिथि",
    ageLimit: "आयु सीमा",
    posts: "पद",
    seeNotice: "आधिकारिक सूचना देखें",
  },
} as const;

export type UiKey = keyof typeof UI.en;
